### ISSUE TITLE
Flux doesn't played

### ISSUE THREAD

**Issue by Catskan-zz** [ampache/ampache#1212]
# Environment
- Ampache version: 3.8.2
- Web server + version: Apache 2 + php 7
- Server operating system: Ubuntu 16.04 LTS
- Client operating system: Windows/OS X
- Client type:
  - [ x] Web
  - [x ] Ampache
  - [ ] SubSonic
  - [ ] Plex
  - [ ] DAAP
  - [ ] UPnP
  - [ ] WebDAV
- Client application + version: 
# Settings

[ampache.cfg.txt](https://github.com/ampache/ampache/files/236201/ampache.cfg.txt)
# Description

I selected "Flux" in Player mode, firefox download the file .m3u generated by Ampache, but it's not played with any music player.
For exemple, VLC have this error : 
![error ampache](https://cloud.githubusercontent.com/assets/17289964/14811913/e885417c-0b9a-11e6-8072-04a8bf79ee8a.PNG)

There is there anything to do?

**Comment by Afterster** [comment]
Please provide some **logs** @Catskan as required. Also, your port (8458) looks weird for me for a `free.fr` hosting, but maybe this provider changed since I knew it.
Is your musing playing on your web browser if you select "Web player" instead of "Stream"?

**Comment by Catskan** [comment]
Hi,

I haven't find the detailed logs file ... Where is it ?

I change the default port for acces it from my works. But I can change this by a other port ? 

Yes, with the web player, it's ok. I can use only the web player ... That is why I am using an external player

**Comment by Afterster** [comment]
OK, then logs are required.
See https://github.com/ampache/ampache/wiki/Troubleshooting#enable-logging

**Comment by Catskan** [comment]
Hi,

It's my log file :

[ampache.20160529.log.zip](https://github.com/ampache/ampache/files/288342/ampache.20160529.log.zip)

**Comment by Phyks** [comment]
There does not seem to be flux related errors in this log file. But you have many MPD related errors.

Can you check using the latest commit on `develop` branch, see if it is fixed? If it is not the case, we could have a deeper look at it.

**Comment by Catskan** [comment]
Hi,

Sorry for the time ... I finally have time to take care of my server ! 

I've downloaded the develop branch `https://github.com/ampache/ampache.git` and I can't access on my new ampache ... Redirecting on test.php and it's a blank page.

Apache log : 
`PHP Fatal error:  Uncaught Error: Class 'Gettext\\Translator' not found in /var/www/html/ampache/lib/i18n.php:36\nStack trace:\n#0 /var/www/html/ampache/test.php(66): load_gettext()\n#1 {main}\n  thrown in /var/www/html/ampache/lib/i18n.php on line 36`

**Comment by Phyks** [comment]
Did you run `composer update` after downloading the `develop` branch?

**Comment by Catskan** [comment]
Oh yes, it works now but I can't add a new catalog because I have two strange error messages : 
` PHP Fatal error:  Uncaught Exception: Missing php-soundcloud dependency. in /var/www/html/ampache/modules/catalog/soundcloud/soundcloud.catalog.php:149\nStack trace:\n#0 /var/www/html/ampache/lib/class/catalog.class.php(248): Catalog_soundcloud->__construct()\n#1 /var/www/html/ampache/templates/show_catalog_types.inc.php(38): Catalog::create_catalog_type('soundcloud')\n#2 /var/www/html/ampache/admin/modules.php(199): require_once('/var/www/html/a...')\n#3 {main}\n  thrown in /var/www/html/ampache/modules/catalog/soundcloud/soundcloud.catalog.php on line 149, referer: http://192.168.1.14/ampache/index.php`

`PHP Fatal error:  Uncaught Exception: Missing xbmc-php-rpc dependency. in /var/www/html/ampache/modules/localplay/xbmc/xbmc.controller.php:53\nStack trace:\n#0 /var/www/html/ampache/lib/class/localplay.class.php(112): AmpacheXbmc->__construct()\n#1 /var/www/html/ampache/lib/class/localplay.class.php(57): Localplay->_load_player()\n#2 /var/www/html/ampache/lib/class/localplay.class.php(45): Localplay->_get_info()\n#3 /var/www/html/ampache/templates/show_localplay_controllers.inc.php(38): Localplay->__construct('xbmc')\n#4 /var/www/html/ampache/admin/modules.php(193): require_once('/var/www/html/a...')\n#5 {main}\n  thrown in /var/www/html/ampache/modules/localplay/xbmc/xbmc.controller.php on line 53, referer: http://192.168.1.14/ampache/index.php`

I don't understand why xbmc and soundcloud are here.

**Comment by Phyks** [comment]
They should be installed by `composer` as well, that's weird (https://github.com/ampache/ampache/blob/develop/composer.lock). They are needed for soundcloud catalog module (https://github.com/ampache/ampache/tree/develop/modules/catalog) and for XBMC/Kodi localplay.

**Comment by Catskan** [comment]
Hi,

I came back to my holidays and I setting up my mpd on my server but ampache can't works with Localplay.
I add a new instance but not works. When I click on play, nothing is happening.

In my mpd.log, I have : `Aug 25 21:40 : curl: curl failed: The requested URL returned error: 404 Not Found
Aug 25 21:40 : player: played "http://192.168.1.14/ampache/play/ssid/9666eb0401e88a699419b7a53e591308/type/song/oid/11058/uid/1/name/VA%20-%20Piste%209.mp3"`

I don't understand ...

It is the same with a instance "localhost", "127.0.0.1" and "192.168.14" ...

Thanks for your help

**Comment by Phyks** [comment]
Can you try to manually reach out `http://192.168.1.14/ampache/play/ssid/9666eb0401e88a699419b7a53e591308/type/song/oid/11058/uid/1/name/VA%20-%20Piste%209.mp3`?

Your issue is simply that the instance URL is not set properly, and the server cannot access the song URL.

What is your setup? What is `192.168.1.14`? (IP of mpd server or ampache server ?) Are mpd and ampache servers on the same network?

See [this comment](https://github.com/ampache/ampache/issues/1203#issuecomment-228155210) and the following ones for extra info on this issue you are experiencing.

**Comment by Catskan** [comment]
Hi,

When I try manually, I have `404 Not Found. The requested URL 192.168.1.14/... was not found on this server`.

192.168.1.14 is my ampache and mpd server. They are on the same PC.

In my mpd.log, I have : 
```
Sep 01 18:34 : client: [0] opened from 192.168.1.14:39102
Sep 01 18:34 : alsa_mixer: Failed to read mixer for 'My ALSA Device': no such mixer control: PCM
Sep 01 18:34 : client: [0] closed
Sep 01 18:34 : curl: curl failed: The requested URL returned error: 404 Not Found
Sep 01 18:34 : player: played "http://192.168.1.14/ampache/play/ssid/244a2ca7e890684a1bc58af3043c086d/type/song/oid/10696/uid/1/name/Rammstein%20-%20-100%20Jahre%20Rammstein-%20Arena%20Be.mp3"
```

**Comment by Phyks** [comment]
Have you enabled URL rewriting? Looks like this is the issue, you should not get a 404 on given URL.

**Comment by Catskan** [comment]
Yes, mod rewrite is enable.

```
a2enmod rewrite
Module rewrite already enabled
```

**Comment by Phyks** [comment]
Do you have anything in your apache log? Have you installed .htaccess files properly?

It definitely sounds like a rewrite config error.

**Comment by Catskan** [comment]
I have not any file in my /var/log/ampache and I have any .htaccess in my /var/www/html .

I have to put anything in the .htaccess file ?

**Comment by Phyks** [comment]
Weird that you do not have any file in `/var/log/ampache`. What is your distribution? It can be in `/var/log/httpd` on some Linuxes. Check that logging is indeed enabled.

Where is Ampache installed? Is it at `/var/www/html`? or at `/var/www/html/ampache`?

You need `mod_rewrite` to enable rewriting (you have this one enabled I think, according to previous comment) and a `.htaccess` containing rewrite rules.

As I understand the wiki, rewriting is not enabled by default and `.htaccess` files may not be installed out of the box. Please:
1. Check if you have a `.htaccess` file containing `RewriteRule` rules at the root of your Ampache install. If not, proceed with next point.
2. Check if you have a `.htaccess` file containing `RewriteRule` rules under `rest`, `play` and `channel` folder. If not, rename the `.htaccess.dist` file provided by Ampache to `.htaccess` for each of these folders.

After having done this, your previous URL starting by `192.168.1.14` should no longer give a 404. Then, if this URL works, your flux setup should be working too.

Let me know how it is going.

**Comment by Catskan** [comment]
I have Ubuntu 16.04, my apache log are in /var/log/apache but I haven't any ampache log.

Ampache is installed in /var/www/html/ampache.

In /var/www/html/ampache/rest/.htacces : 
```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-s
    RewriteRule ^(.+)\.view$ /rest/index.php?ssaction=$1 [PT,L,QSA]
    RewriteRule ^fake/(.+)$ /play/$1 [PT,L,QSA]
</IfModule>
```

In /var/www/html/ampache/play/.htaccess : 
```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-s
    RewriteRule /var/www/html/ampache/image.php?object_type=$2&object_id=$3&auth=$1&thumb=$4&name=art.jpg [L]
    RewriteRule /var/www/html/ampache/play/$5?$1=$2&$3=$4 [N,QSA]
    RewriteRule /var/www/html/ampache/play/$3?$1=$2 [N,QSA]
    RewriteRule /var/www/html/ampache/play/index.php [L,QSA]
</IfModule>
```

In /var/www/html/ampache/channel/.htacces : 
```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-s
    RewriteRule ^([0-9]+)/(.*)$ /channel/index.php?channel=$1&target=$2 [PT,L,QSA]
</IfModule>
```

My access.log (apache) : 
```
192.168.1.2 - - [02/Sep/2016:20:22:04 +0200] "POST /ampache/server/ajax.server.php?page=stream&action=directplay&object_type=song&object_id=2738 HTTP/1.1" 200 647 "http://192.168.1.14/ampache/index.php" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0"
192.168.1.2 - - [02/Sep/2016:20:22:05 +0200] "GET /ampache/util.php HTTP/1.1" 302 464 "http://192.168.1.14/ampache/index.php" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0"
192.168.1.2 - - [02/Sep/2016:20:22:05 +0200] "GET /ampache/stream.php?action=play_item&object_type=song&object_id=2738 HTTP/1.1" 200 312 "http://192.168.1.14/ampache/index.php" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0"
192.168.1.14 - - [02/Sep/2016:20:22:05 +0200] "GET /ampache/play/ssid/39e60fa69503e77ac605222335c9dd57/type/song/oid/2738/uid/1/name/Mr.%20Belt%20-%20Wezol%20-%20Finally%20-Original%20Mix-.mp3 HTTP/1.1" 404 563 "-" "Music Player Daemon 0.19.12"
192.168.1.2 - - [02/Sep/2016:20:22:11 +0200] "POST /ampache/server/ajax.server.php?page=index&action=reloadnp HTTP/1.1" 200 3338 "http://192.168.1.14/ampache/index.php" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:48.0) Gecko/20100101 Firefox/48.0"
```

192.168.1.2 : My PC to witch I am connected to my ampache server.
192.168.1.14 : My Ampache / MPD Server

**Comment by Phyks** [comment]
Thanks for the Apache logs, they do not tell us much though…


Your `/var/www/html/ampache/play/.htaccess` looks weird though. Mine (default one provided with Ampache) reads:
```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-s
    RewriteRule ^art/([^/]+)/([^/]+)/([0-9]+)/thumb([0-9]*)\.([a-z]+)$ /image.php?object_type=$2&object_id=$3&auth=$1&thumb=$4&name=art.jpg [L]
    RewriteRule ^([^/]+)/([^/]+)/([^/]+)/([^/]+)(/.*)?$ /play/$5?$1=$2&$3=$4 [N,QSA]
    RewriteRule ^([^/]+)/([^/]+)(/.*)?$ /play/$3?$1=$2 [N,QSA]
    RewriteRule ^(/[^/]+|[^/]+/|/?)$ /play/index.php [L,QSA]
</IfModule>
```

I think you have a faulty htaccess there, and this is why you are experiencing such errors with flux.

**Comment by Catskan** [comment]
Ah ? Is the default .htaccess .

How can I make a correct .htaccess ?

**Comment by Phyks** [comment]
Hmm, it may be a bug in `.htaccess` generation. Your file writes:
```
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-s
    RewriteRule /var/www/html/ampache/image.php?object_type=$2&object_id=$3&auth=$1&thumb=$4&name=art.jpg [L]
    RewriteRule /var/www/html/ampache/play/$5?$1=$2&$3=$4 [N,QSA]
    RewriteRule /var/www/html/ampache/play/$3?$1=$2 [N,QSA]
    RewriteRule /var/www/html/ampache/play/index.php [L,QSA]
```

as far as I understood but these rewrite rules are invalid and lack a part (the match part). Typically,
```
RewriteRule /var/www/html/ampache/play/index.php [L,QSA]
```
should instead be something like
```
RewriteRule ^(/[^/]+|[^/]+/|/?)$ /var/www/html/ampache/play/index.php [L,QSA]
```

Could you try with [this .htaccess file](https://github.com/ampache/ampache/blob/develop/play/.htaccess.dist). I guess it should work.

I am not an Apache user, nor is @Niols I think. I am not sure what could have happened with the .htaccess generation. If any Apache user has some input on this, it would be very useful.

**Comment by Catskan** [comment]
Ah ok ! But, with your .htaccess, still doesn't works ...

My access.log : 
```
htpc@htpc-H87N-WIFI:~$ cat /var/log/apache2/access.log
192.168.1.2 - - [07/Sep/2016:20:32:46 +0200] "POST /ampache/server/ajax.server.p                                                                                                                                                             hp?page=index&action=reloadnp HTTP/1.1" 200 2972 "http://192.168.1.14/ampache/in                                                                                                                                                             dex.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, l                                                                                                                                                             ike Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586"
192.168.1.2 - - [07/Sep/2016:20:32:56 +0200] "POST /ampache/server/ajax.server.p                                                                                                                                                             hp?page=stream&action=directplay&object_type=song&object_id=7279 HTTP/1.1" 200 6                                                                                                                                                             45 "http://192.168.1.14/ampache/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64;                                                                                                                                                              x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Ed                                                                                                                                                             ge/13.10586"
192.168.1.2 - - [07/Sep/2016:20:32:56 +0200] "GET /ampache/util.php HTTP/1.1" 30                                                                                                                                                             2 464 "http://192.168.1.14/ampache/index.php" "Mozilla/5.0 (Windows NT 10.0; Win                                                                                                                                                             64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36                                                                                                                                                              Edge/13.10586"
192.168.1.2 - - [07/Sep/2016:20:32:56 +0200] "GET /ampache/stream.php?action=pla                                                                                                                                                             y_item&object_type=song&object_id=7279 HTTP/1.1" 302 445 "http://192.168.1.14/am                                                                                                                                                             pache/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (                                                                                                                                                             KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586"
192.168.1.2 - - [07/Sep/2016:20:32:56 +0200] "GET /ampache/play/index.php?ssid=c                                                                                                                                                             3b148cf55878c6c3792d57e9929bd38&uid=1&type=playlist&playlist_type=m3u HTTP/1.1"                                                                                                                                                              200 442 "http://192.168.1.14/ampache/index.php" "Mozilla/5.0 (Windows NT 10.0; W                                                                                                                                                             in64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.                                                                                                                                                             36 Edge/13.10586"
192.168.1.2 - - [07/Sep/2016:20:33:04 +0200] "POST /ampache/server/ajax.server.p                                                                                                                                                             hp?page=index&action=reloadnp HTTP/1.1" 200 2972 "http://192.168.1.14/ampache/in                                                                                                                                                             dex.php" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:48.0) Gecko/20100101 Firefox/4                                                                                                                                                             8.0"
```

error.log : 
```
htpc@htpc-H87N-WIFI:~$ cat /var/log/apache2/error.log
[Wed Sep 07 20:32:45.881435 2016] [so:warn] [pid 12680] AH01574: module access_compat_module is already loaded, skipping
[Wed Sep 07 20:32:45.881559 2016] [so:warn] [pid 12680] AH01574: module alias_module is already loaded, skipping
[Wed Sep 07 20:32:45.881580 2016] [so:warn] [pid 12680] AH01574: module auth_basic_module is already loaded, skipping
[Wed Sep 07 20:32:45.881597 2016] [so:warn] [pid 12680] AH01574: module authn_core_module is already loaded, skipping
[Wed Sep 07 20:32:45.881615 2016] [so:warn] [pid 12680] AH01574: module authn_file_module is already loaded, skipping
[Wed Sep 07 20:32:45.881628 2016] [so:warn] [pid 12680] AH01574: module authz_core_module is already loaded, skipping
[Wed Sep 07 20:32:45.881639 2016] [so:warn] [pid 12680] AH01574: module authz_host_module is already loaded, skipping
[Wed Sep 07 20:32:45.881654 2016] [so:warn] [pid 12680] AH01574: module authz_user_module is already loaded, skipping
[Wed Sep 07 20:32:45.881670 2016] [so:warn] [pid 12680] AH01574: module autoindex_module is already loaded, skipping
[Wed Sep 07 20:32:45.881687 2016] [so:warn] [pid 12680] AH01574: module deflate_module is already loaded, skipping
[Wed Sep 07 20:32:45.881702 2016] [so:warn] [pid 12680] AH01574: module dir_module is already loaded, skipping
[Wed Sep 07 20:32:45.881716 2016] [so:warn] [pid 12680] AH01574: module env_module is already loaded, skipping
[Wed Sep 07 20:32:45.881730 2016] [so:warn] [pid 12680] AH01574: module filter_module is already loaded, skipping
[Wed Sep 07 20:32:45.881742 2016] [so:warn] [pid 12680] AH01574: module mime_module is already loaded, skipping
[Wed Sep 07 20:32:45.881764 2016] [so:warn] [pid 12680] AH01574: module mpm_prefork_module is already loaded, skipping
[Wed Sep 07 20:32:45.881783 2016] [so:warn] [pid 12680] AH01574: module negotiation_module is already loaded, skipping
[Wed Sep 07 20:32:45.881798 2016] [so:warn] [pid 12680] AH01574: module php7_module is already loaded, skipping
[Wed Sep 07 20:32:45.881812 2016] [so:warn] [pid 12680] AH01574: module rewrite_module is already loaded, skipping
[Wed Sep 07 20:32:45.881828 2016] [so:warn] [pid 12680] AH01574: module setenvif_module is already loaded, skipping
[Wed Sep 07 20:32:45.881844 2016] [so:warn] [pid 12680] AH01574: module status_module is already loaded, skipping
[Wed Sep 07 20:32:45.921222 2016] [mpm_prefork:notice] [pid 12681] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Wed Sep 07 20:32:45.921252 2016] [core:notice] [pid 12681] AH00094: Command line: '/usr/sbin/apache2'
```

and /play/.htaccess : 
```
<IfModule mod_rewrite.c>
    RewriteEngine On
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_FILENAME} !-s
    RewriteRule ^art/([^/]+)/([^/]+)/([0-9]+)/thumb([0-9]*)\.([a-z]+)$ /image.php?object_type=$2&object_id=$3&auth=$1&thumb=$4&name=art.jpg [L]
    RewriteRule ^([^/]+)/([^/]+)/([^/]+)/([^/]+)(/.*)?$ /play/$5?$1=$2&$3=$4 [N,QSA]
    RewriteRule ^([^/]+)/([^/]+)(/.*)?$ /play/$3?$1=$2 [N,QSA]
    RewriteRule ^(/[^/]+|[^/]+/|/?)$ /play/index.php [L,QSA]
</IfModule>
```

Finally, I don't understand ... Is it Apache did not works with the ampache Flux/Localplay ?

I tryied to install nginx so ...

**Comment by Phyks** [comment]
Hmm, give me some time so that I set up a working Apache setup and try to reproduce to help you better. 

Both me and @Niols are using a nginx based setup, and developers who used to have an Apache setup are not very active at the moment. But Ampache should work with Apache, actually it is kind of the standard setup. 

Le 7 septembre 2016 20:39:51 UTC+02:00, Catskan <notifications@github.com> a écrit :
>Ah ok ! But, with your .htaccess, still doesn't works ...
>
>My access.log : 
>```
>htpc@htpc-H87N-WIFI:~$ cat /var/log/apache2/access.log
>192.168.1.2 - - [07/Sep/2016:20:32:46 +0200] "POST
>/ampache/server/ajax.server.p                                          
>hp?page=index&action=reloadnp HTTP/1.1" 200 2972
>"http://192.168.1.14/ampache/in                                        
>dex.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
>(KHTML, l                                                              
>             ike Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586"
>192.168.1.2 - - [07/Sep/2016:20:32:56 +0200] "POST
>/ampache/server/ajax.server.p                                          
>hp?page=stream&action=directplay&object_type=song&object_id=7279
>HTTP/1.1" 200 6                                                        
>45 "http://192.168.1.14/ampache/index.php" "Mozilla/5.0 (Windows NT
>10.0; Win64;                                                           
>x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0
>Safari/537.36 Ed                                                       
>                                                           ge/13.10586"
>192.168.1.2 - - [07/Sep/2016:20:32:56 +0200] "GET /ampache/util.php
>HTTP/1.1" 30                                                           
>2 464 "http://192.168.1.14/ampache/index.php" "Mozilla/5.0 (Windows NT
>10.0; Win                                                              
>64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0
>Safari/537.36                                                          
>                                                         Edge/13.10586"
>192.168.1.2 - - [07/Sep/2016:20:32:56 +0200] "GET
>/ampache/stream.php?action=pla                                         
>y_item&object_type=song&object_id=7279 HTTP/1.1" 302 445
>"http://192.168.1.14/am                                                
>pache/index.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64)
>AppleWebKit/537.36 (                                                   
>     KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36 Edge/13.10586"
>192.168.1.2 - - [07/Sep/2016:20:32:56 +0200] "GET
>/ampache/play/index.php?ssid=c                                         
>3b148cf55878c6c3792d57e9929bd38&uid=1&type=playlist&playlist_type=m3u
>HTTP/1.1"                                                              
>200 442 "http://192.168.1.14/ampache/index.php" "Mozilla/5.0 (Windows
>NT 10.0; W                                                             
>in64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0
>Safari/537.                                                            
>                                                      36 Edge/13.10586"
>192.168.1.2 - - [07/Sep/2016:20:33:04 +0200] "POST
>/ampache/server/ajax.server.p                                          
>hp?page=index&action=reloadnp HTTP/1.1" 200 2972
>"http://192.168.1.14/ampache/in                                        
>dex.php" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:48.0) Gecko/20100101
>Firefox/4                                                              
>                                                                   8.0"
>```
>
>error.log : 
>```
>htpc@htpc-H87N-WIFI:~$ cat /var/log/apache2/error.log
>[Wed Sep 07 20:32:45.881435 2016] [so:warn] [pid 12680] AH01574: module
>access_compat_module is already loaded, skipping
>[Wed Sep 07 20:32:45.881559 2016] [so:warn] [pid 12680] AH01574: module
>alias_module is already loaded, skipping
>[Wed Sep 07 20:32:45.881580 2016] [so:warn] [pid 12680] AH01574: module
>auth_basic_module is already loaded, skipping
>[Wed Sep 07 20:32:45.881597 2016] [so:warn] [pid 12680] AH01574: module
>authn_core_module is already loaded, skipping
>[Wed Sep 07 20:32:45.881615 2016] [so:warn] [pid 12680] AH01574: module
>authn_file_module is already loaded, skipping
>[Wed Sep 07 20:32:45.881628 2016] [so:warn] [pid 12680] AH01574: module
>authz_core_module is already loaded, skipping
>[Wed Sep 07 20:32:45.881639 2016] [so:warn] [pid 12680] AH01574: module
>authz_host_module is already loaded, skipping
>[Wed Sep 07 20:32:45.881654 2016] [so:warn] [pid 12680] AH01574: module
>authz_user_module is already loaded, skipping
>[Wed Sep 07 20:32:45.881670 2016] [so:warn] [pid 12680] AH01574: module
>autoindex_module is already loaded, skipping
>[Wed Sep 07 20:32:45.881687 2016] [so:warn] [pid 12680] AH01574: module
>deflate_module is already loaded, skipping
>[Wed Sep 07 20:32:45.881702 2016] [so:warn] [pid 12680] AH01574: module
>dir_module is already loaded, skipping
>[Wed Sep 07 20:32:45.881716 2016] [so:warn] [pid 12680] AH01574: module
>env_module is already loaded, skipping
>[Wed Sep 07 20:32:45.881730 2016] [so:warn] [pid 12680] AH01574: module
>filter_module is already loaded, skipping
>[Wed Sep 07 20:32:45.881742 2016] [so:warn] [pid 12680] AH01574: module
>mime_module is already loaded, skipping
>[Wed Sep 07 20:32:45.881764 2016] [so:warn] [pid 12680] AH01574: module
>mpm_prefork_module is already loaded, skipping
>[Wed Sep 07 20:32:45.881783 2016] [so:warn] [pid 12680] AH01574: module
>negotiation_module is already loaded, skipping
>[Wed Sep 07 20:32:45.881798 2016] [so:warn] [pid 12680] AH01574: module
>php7_module is already loaded, skipping
>[Wed Sep 07 20:32:45.881812 2016] [so:warn] [pid 12680] AH01574: module
>rewrite_module is already loaded, skipping
>[Wed Sep 07 20:32:45.881828 2016] [so:warn] [pid 12680] AH01574: module
>setenvif_module is already loaded, skipping
>[Wed Sep 07 20:32:45.881844 2016] [so:warn] [pid 12680] AH01574: module
>status_module is already loaded, skipping
>[Wed Sep 07 20:32:45.921222 2016] [mpm_prefork:notice] [pid 12681]
>AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal
>operations
>[Wed Sep 07 20:32:45.921252 2016] [core:notice] [pid 12681] AH00094:
>Command line: '/usr/sbin/apache2'
>```
>
>and /play/.htaccess : 
>```
><IfModule mod_rewrite.c>
>    RewriteEngine On
>    RewriteCond %{REQUEST_FILENAME} !-d
>    RewriteCond %{REQUEST_FILENAME} !-s
>RewriteRule ^art/([^/]+)/([^/]+)/([0-9]+)/thumb([0-9]*)\.([a-z]+)$
>/image.php?object_type=$2&object_id=$3&auth=$1&thumb=$4&name=art.jpg
>[L]
>RewriteRule ^([^/]+)/([^/]+)/([^/]+)/([^/]+)(/.*)?$
>/play/$5?$1=$2&$3=$4 [N,QSA]
>    RewriteRule ^([^/]+)/([^/]+)(/.*)?$ /play/$3?$1=$2 [N,QSA]
>    RewriteRule ^(/[^/]+|[^/]+/|/?)$ /play/index.php [L,QSA]
></IfModule>
>```
>
>Finally, I don't understand ... Is it Apache did not works with the
>ampache Flux/Localplay ?
>
>I tryied to install nginx so ...
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/ampache/ampache/issues/1212#issuecomment-245376747

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by Catskan** [comment]
Oh thanks you very much ! I eagerly awaits your return :).

**Comment by Catskan** [comment]
Hi guys,

I had setted up my ampache server with nginx, but I can't always use Localplay ou Flux to use with an external app. I have same errors ...

Error.log : 

> 2016/12/07 21:35:17 [error] 8590#8590: *40 open() "/var/www/html/ampache/ampache/play/ssid/b36a47ee750a0cedd84a80e1bba061b8/type/song/oid/13856/uid/1/name/DJ Battle - Twerk Lesson -feat. Lexy Panterra-.mp3" failed (2: No such file or directory), client: 192.168.1.254, server: catskan.hd.free.fr, request: "GET /ampache/play/ssid/b36a47ee750a0cedd84a80e1bba061b8/type/song/oid/13856/uid/1/name/DJ%20Battle%20-%20Twerk%20Lesson%20-feat.%20Lexy%20Panterra-.mp3 HTTP/1.1", host: "catskan.hd.free.fr", referrer: "http://catskan.hd.free.fr/ampache/util.php"

I don't understand ...

**Comment by mitchray** [comment]
Closing due to inactivity
