### ISSUE TITLE
PHP Fatal error when upload a mp3 file

### ISSUE THREAD

**Issue by atitan** [ampache/ampache#1499]
# Environment

 * Ampache version: cd761ccc3b997ee0e219c81dd6cdf2668e70f734
 * Web server + version: Nginx 1.10.2 with http2 and SSL
 * Server operating system: Fedora 25
 * Client operating system: Windows 7 + Chrome 56

 * Client type:
   - Web

# Description

I uploaded mp3 file using the web GUI, and it triggered PHP error when upload was finished.

The song uploaded can be found in the catalog and local disk, but the metadata, such as artist or album, is missing.

I'll have to update the catalog manually to get these information back.

# Logs

```
PHP message: PHP Fatal error:  Uncaught Error: Using $this when not in object context in /usr/share/nginx/ampache/lib/class/song.class.php:428
Stack trace:
#0 /usr/share/nginx/ampache/modules/catalog/local/local.catalog.php(746): Song::insert(Array)
#1 /usr/share/nginx/ampache/modules/catalog/local/local.catalog.php(378): Catalog_local->insert_local_song('/var/ampache/at...', Array)
#2 /usr/share/nginx/ampache/lib/class/upload.class.php(168): Catalog_local->add_file('/var/ampache/at...', Array)
#3 /usr/share/nginx/ampache/upload.php(49): Upload::process()
#4 {main}
  thrown in /usr/share/nginx/ampache/lib/class/song.class.php on line 428
```

**Comment by atitan** [comment]
I made a patch to solve this: https://github.com/ampache/ampache/pull/1502
