### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Call to a member function get_rel_path() on null in /usr/share/webapps/ampache/lib/class/song.class.php:1698

### ISSUE THREAD

**Issue by BoBeR182** [ampache/ampache#1664]
# Environment

 * Ampache version: 3.8.5-release
 * Web server + version: apache 2.4.29-1
 * Server operating system: Arch Linux
 * Client operating system: Android Lineage OS 14.1

 * Client type:
   - DSub 5.3.5

# Settings

Stock settings

# Description

When I open the server in Dsub and hit random songs to get a playlist loaded. I get error 500 in logcat. When I check the server logs I have the following output.

# Logs

```[php7:error] [pid 14119] [client 192.168.1.7:39432] PHP Fatal error:  Uncaught Error: Call to a member function get_rel_path() on null in /usr/share/webapps/ampache/lib/class/song.class.php:1698\nStack trace:\n#0 /usr/share/webapps/ampache/lib/class/subsonic_xml_data.class.php(493): Song->get_rel_path()\n#1 /usr/share/webapps/ampache/lib/class/subsonic_xml_data.class.php(435): Subsonic_XML_Data::createSong(Object(SimpleXMLElement), Object(Song), false, 'song')\n#2 /usr/share/webapps/ampache/lib/class/subsonic_xml_data.class.php(694): Subsonic_XML_Data::addSong(Object(SimpleXMLElement), Object(Song))\n#3 /usr/share/webapps/ampache/lib/class/subsonic_api.class.php(715): Subsonic_XML_Data::addRandomSongs(Object(SimpleXMLElement), Array)\n#4 /usr/share/webapps/ampache/rest/index.php(163): Subsonic_Api::getrandomsongs(Array)\n#5 {main}\n  thrown in /usr/share/webapps/ampache/lib/class/song.class.php on line 1698```

**Comment by wagnered** [comment]
@BoBeR182 

The code appears to indicate that it is looking for a non-existent file path (thus the null).
I suggest doing a clean of all your catalogs and try again.  Otherwise, I cannot duplicate your issue using DSub.

I marked this a bug for not trapping the error and suggesting that a catalog might need cleaning. Hope this helps. 😄

**Comment by BoBeR182** [comment]
Did a clean and a verify, no changes still produces error 500, and apache logs show the same info.
Only feature that works in DSub is recent songs to load up a playlist.

Here are the logs from trying to use recently added or random playlist loading features.

``` [client 192.168.1.7:43845] PHP Fatal error:  Uncaught Error: Call to a member function get_rel_path() on null in /usr/share/webapps/ampache/lib/class/song.class.php:1698\nStack trace:\n#0 /usr/share/webapps/ampache/lib/class/subsonic_xml_data.class.php(493): Song->get_rel_path()\n#1 /usr/share/webapps/ampache/lib/class/subsonic_xml_data.class.php(435): Subsonic_XML_Data::createSong(Object(SimpleXMLElement), Object(Song), false, 'song')\n#2 /usr/share/webapps/ampache/lib/class/subsonic_xml_data.class.php(694): Subsonic_XML_Data::addSong(Object(SimpleXMLElement), Object(Song))\n#3 /usr/share/webapps/ampache/lib/class/subsonic_api.class.php(715): Subsonic_XML_Data::addRandomSongs(Object(SimpleXMLElement), Array)\n#4 /usr/share/webapps/ampache/rest/index.php(163): Subsonic_Api::getrandomsongs(Array)\n#5 {main}\n  thrown in /usr/share/webapps/ampache/lib/class/song.class.php on line 1698```


```[client 192.168.1.7:43867] PHP Fatal error:  Uncaught Error: Call to a member function get_rel_path() on null in /usr/share/webapps/ampache/lib/class/song.class.php:1698\nStack trace:\n#0 /usr/share/webapps/ampache/lib/class/subsonic_xml_data.class.php(493): Song->get_rel_path()\n#1 /usr/share/webapps/ampache/lib/class/subsonic_xml_data.class.php(435): Subsonic_XML_Data::createSong(Object(SimpleXMLElement), Object(Song), false, 'child')\n#2 /usr/share/webapps/ampache/lib/class/subsonic_xml_data.class.php(571): Subsonic_XML_Data::addSong(Object(SimpleXMLElement), Object(Song), false, 'child')\n#3 /usr/share/webapps/ampache/lib/class/subsonic_api.class.php(433): Subsonic_XML_Data::addAlbumDirectory(Object(SimpleXMLElement), Object(Album))\n#4 /usr/share/webapps/ampache/rest/index.php(163): Subsonic_Api::getmusicdirectory(Array)\n#5 {main}\n  thrown in /usr/share/webapps/ampache/lib/class/song.class.php on line 1698```

**Comment by wagnered** [comment]
Please enable debug log in ampache.cfg.php and post result. I'm running Ampache-3.8.6-develop with no problems with DSub but will revert to 3.8.5-release and try.

**Comment by wagnered** [comment]
@BoBeR182 

I've just tested 3.8.5-release and found no problems with DSub.
I'm thinking possibly a corrupted catalog or it might have collected bad data from  one of the files.

If you re-create the catalog, all files should have the "Recently added" status and should cause a problem with  DSub if one of the files caused bad data to be collected.

**Comment by BoBeR182** [comment]
Removing and readding the catalog did not resolve the issue.
Here is the ampache logs.
```
[ampache] (PHP) -> [Runtime Error] Invalid argument supplied for foreach() in file /usr/share/webapps/ampache/lib/class/subsonic_xml_data.class.php(723)
[ampache] (PHP) -> [Runtime Error] Invalid argument supplied for foreach() in file /usr/share/webapps/ampache/lib/class/subsonic_xml_data.class.php(727) 
```

**Comment by wagnered** [comment]
@BoBeR182 

When you select "Recently Added" from DSub, do you get the same result as before re-creating the catalog?

If so, does the DSub "Starred" function work?  I suggest you select several songs you know are playable while logged into the web interface and set them as favorites. If the DSub "Starred" function retrieves them, then there is probably a file with bad data in the catalog.

As I said, I cannot duplicate your issue and am out of ideas.

**Comment by BoBeR182** [comment]
I have no songs load up from the server in Recently Added, it also does not show the star with a number in it as it would when you have new songs. 

I played a few songs over the web interface, and then was able to load them in the recently played option of DSub, how would I trace what song has corrupted the catalog?

**Comment by wagnered** [comment]
@BoBeR182 

Sorry to take so long to get back to you.

 > how would I trace what song has corrupted the catalog?

I'm not sure about the best way.  I would start by putting the songs thru a mass tagger. I like Easytag:  It is good for flac and mp3 files. Some of the songs may be tagged with characters encoded as UTF16 which causes problems with Ampache. The character encodeng can be set in Easytag for writing the modified files.

Sorry I can't be of more help.
