### ISSUE TITLE
Adding catalog with square brackets in the folder pattern leads to a PHP fatal error

### ISSUE THREAD

**Issue by axelsimon** [ampache/ampache#1840]
Hi, just caught this and thought I'd share.

# Environment

 * Ampache version: 3.9.1-develop
 * Web server + version: nginx 1.14.2
 * Server operating system: Debian Buster (10)
 * Client operating system: Fedora 29

# Description

When adding a catalog of local music, Ampache asks for information regarding the structure of the folders.
My structure is typically: `artist/[YYYY-MM-DD] album title (version/catalog number/extra stuff) (codec + bitrate if applicable)` so I entered `%a/\[%y\] %A (%o)` in the catalog's dialog's "folder pattern".
The catalog scanner then doesn't find any songs, throws a "Server-Sent Events connecton error. Re-Connection…" error on a loop and the error log shows an error.

# Logs
```
2019/01/04 10:49:14 [error] 17811#17811: *193828 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /opt/ampache/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php:464
Stack trace:
#0 /opt/ampache/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php(1098): getid3_mp3->decodeMPEGaudioHeader(108, Array, false)
#1 /opt/ampache/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php(889): getid3_mp3->RecursiveFrameScanning(0, 108, true)
#2 /opt/ampache/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php(1430): getid3_mp3->decodeMPEGaudioHeader(0, Array, true)
#3 /opt/ampache/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php(35): getid3_mp3->getOnlyMPEGaudioInfo(0)
#4 /opt/ampache/lib/vendor/james-heinrich/getid3/getid3/getid3.php(450): getid3_mp3->Analyze()
#5 /opt/ampache/lib/class/vainfo.class.php(96): getID3->analyze('/mnt/music/...')
#6 /opt/ampache/modules/catalog/local/local.catalog.php(697): vainfo->__construct('/mnt/music/...', Array, '', '', '', '%a/\\[%y\\] %A" while reading upstream, client: 192.168.0.1, server: ampache.jaccu.se, request: "GET /server/sse.server.php?worker=catalog&action=add_to_catalog&catalogs=%5B%227%22%5D HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "ampache.example.com", referrer: "https://ampache.example.com/
```

# Workaround
Delete the catalog (updating the folder pattern field isn't enough) and don't put curly brackets in the pattern field, even with `\` to escape them.

**Comment by axelsimon** [comment]
Ok just saw this is a duplicate of https://github.com/ampache/ampache/issues/1451, closing.
