### ISSUE TITLE
Catalog update dies with php error

### ISSUE THREAD

**Issue by lemmy04** [ampache/ampache#1850]
# Environment

 * Ampache version: 3.9.0
 * Web server + version: apache 2.4.33, PHP7 7.3.1
 * Server operating system: openSUSE Leap 15.0
 * Client operating system: openSUSE Leap 15.0

 * Client type:
   - CLI tool bundles with ampache: bin/update_catalog.inc

# Description

Updating the catalog dies with a php error:
PHP Fatal error:  Uncaught Error: [] operator not supported for strings in /srv/www/ampache/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php:926
Stack trace:
#0 /srv/www/ampache/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php(1088): getid3_mp3->decodeMPEGaudioHeader(42664, Array, false)
#1 /srv/www/ampache/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php(973): getid3_mp3->RecursiveFrameScanning(42664, 43081, false)
#2 /srv/www/ampache/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php(1430): getid3_mp3->decodeMPEGaudioHeader(42664, Array, true)
#3 /srv/www/ampache/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php(35): getid3_mp3->getOnlyMPEGaudioInfo(42664)
#4 /srv/www/ampache/lib/vendor/james-heinrich/getid3/getid3/getid3.php(450): getid3_mp3->Analyze()
#5 /srv/www/ampache/lib/class/vainfo.class.php(96): getID3->analyze('/eregion/mp3/Me...')
#6 /srv/www/ampache/lib/class/catalog.class.php(1771): vainfo->__construct('/eregion/mp3/Me...', Array, '', '', '', '%a/%A', '%a  in /srv/www/ampache/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php on line 926
3293
/eregion/mp3/Maxi Singles/Kim Appleby/Dont Worry Maxi Cd/01 Dont Worry 123 BPM Pop.mp3
3313
/eregion/mp3/Maxi Singles/The Simpsons/Do The Bartman/04 Do The Bartman A Cappella.mp3
3481
/eregion/mp3/Maxi Singles/Crash Test Dummies/Mmm Mmm Mmm Mmm/01 Mmm Mmm Mmm Mmm.mp3
3505
/eregion/mp3/Maxi Singles/The Grid/Swamp Thing Single/01 - Swamp Thing Radio Mix.mp3
Fatal error: Uncaught Error: [] operator not supported for strings in /srv/www/ampache/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php:926
Stack trace:
#0 /srv/www/ampache/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php(1088): getid3_mp3->decodeMPEGaudioHeader(42664, Array, false)
#1 /srv/www/ampache/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php(973): getid3_mp3->RecursiveFrameScanning(42664, 43081, false)
#2 /srv/www/ampache/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php(1430): getid3_mp3->decodeMPEGaudioHeader(42664, Array, true)
#3 /srv/www/ampache/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php(35): getid3_mp3->getOnlyMPEGaudioInfo(42664)
#4 /srv/www/ampache/lib/vendor/james-heinrich/getid3/getid3/getid3.php(450): getid3_mp3->Analyze()
#5 /srv/www/ampache/lib/class/vainfo.class.php(96): getID3->analyze('/eregion/mp3/Me...')
#6 /srv/www/ampache/lib/class/catalog.class.php(1771): vainfo->__construct('/eregion/mp3/Me...', Array, '', '', '', '%a/%A', '%a  in /srv/www/ampache/lib/vendor/james-heinrich/getid3/getid3/module.audio.mp3.php on line 926
# Logs

nothing definite in the logs even with debuglevel 5, only progress of the update until it dies.

**Comment by lachlan-00** [comment]
seems like a problem with the file it's trying to parse? the log should say which file it's parsing.

**Comment by lachlan-00** [comment]
you might be able to find it with this line. search above that for the file it's trying to load.
```
analyze('/eregion/mp3/Me...')
```

**Comment by mitchray** [comment]
Closing due to inactivity
