### ISSUE TITLE
Error when running catalog update from command line with Amazon as art source

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#2372]
## Description
Attempting to update my catalogs from the command line. I am getting an error when I enable Amazon as a source for art. May be related to #2333 .

### To reproduce

1. run sudo -u www-data php /var/www/ampache/bin/catalog_update.inc -c -a -g -u -m -o
2. See error
```


----------------------------------------------------------
Starting Catalog operations...
	- Temporarily deactivating PHP memory limit
	- Cleaning Catalog/s
	- Adding new media to Catalog/s
	- Gathering new media art
	- Update artist information and fetch similar artists from last.fm
	- Database table optimization
----------------------------------------------------------

- Deactivated PHP memory limit -
------------------

Reading Catalog: "General Music"
- Start cleaning orphaned media entries - 
           Clean Catalog
Cleaning the "[ General Music ]" Catalog...
Checking: 
Reading: 
1
/home/.../Music/My Music/Guns N Roses/Use Your Illusion I/13 Dont Damn Me.flac
38469
/home/.../Music/My Music/Tears for Fears/Sowing the Seeds of Love_ The Best of Tears for Fears/1-12 Johnny Panic and the Bible of Dreams.flac0 files removed.
------------------
- Start adding new media - 
           Starting New Media Search
Starting New Media Search on "[ General Music ]" Catalog
Found: None
Reading:
0PHP Fatal error:  Uncaught Requests_Exception: cURL error 6: Could not resolve host: 2d656564694f234d656564 in /var/www/ampache/lib/vendor/rmccue/requests/library/Requests/Transport/cURL.php:422
Stack trace:
#0 /var/www/ampache/lib/vendor/rmccue/requests/library/Requests/Transport/cURL.php(177): Requests_Transport_cURL->process_response('', Array)
#1 /var/www/ampache/lib/vendor/rmccue/requests/library/Requests.php(379): Requests_Transport_cURL->request('http://2d656564...', Array, NULL, Array)
#2 /var/www/ampache/lib/vendor/rmccue/requests/library/Requests.php(231): Requests::request('http://2d656564...', Array, NULL, 'GET', Array)
#3 /var/www/ampache/modules/infotools/AmazonSearchEngine.class.php(163): Requests::get('http://2d656564...', Array, Array)
#4 /var/www/ampache/modules/infotools/AmazonSearchEngine.class.php(236): AmazonSearch->runSearch('http://2d656564...')
#5 /var/www/ampache/modules/plugins/Amazon/Amazon.plugin.php(188): AmazonSearch->search(Array, 'Music')
#6 /var/www/ampache/lib/class/art.class.php(1126): Ampac in /var/www/ampache/lib/vendor/rmccue/requests/library/Requests/Transport/cURL.php on line 422
Art Search
Starting Art Search. . .
Searched: None

```

## Environment

* Ampache version: 0aaa5bfb1a0b57345957888d15ac4abded52d83e
* Web server + version: PHP 7.3
* Server operating system: Debian Bullseye
* Client operating system: Debian Bullseye

### Client type

* Ampache

## Settings

```
; Art Gather Order
; Simply arrange the following in the order you would like
; Ampache to search. If you want to disable one of the search
; methods simply leave it out. DB should be left as the first
; method unless you want it to overwrite what's already in the
; database
; POSSIBLE VALUES (builtins): db tags folder lastfm musicbrainz google
; POSSIBLE VALUES (plugins): Amazon,TheAudioDb,Tmdb,Omdb,Flickr
; DEFAULT: db,tags,folder,musicbrainz,lastfm,google
art_order = "db,tags,folder,musicbrainz,lastfm,TheAudioDb,Discogs,Amazon,google"
```

## Logs

```
2020-05-04T06:49:45-04:00 [ampache] (art.class) -> Searching using:["db","tags","folder","musicbrainz","lastfm","TheAudioDb","Discogs","Amazon"] 
2020-05-04T06:49:45-04:00 [ampache] (art.class) -> Method used: gather_db 
2020-05-04T06:49:45-04:00 [ampache] (art.class) -> Method used: gather_tags 
2020-05-04T06:49:45-04:00 [ampache] (art.class) -> Method used: gather_folder 
2020-05-04T06:49:45-04:00 [ampache] (art.class) -> gather_folder: Opening /home/.../Music/My Music/Christine Santelli/Any Better Time and checking for Album Art 
2020-05-04T06:49:45-04:00 [ampache] (art.class) -> gather_folder: Found image file: Christine Santelli - Any Better Time - Inside.jpg 
2020-05-04T06:49:45-04:00 [ampache] (art.class) -> gather_folder: Found image file: Christine Santelli - Any Better Time - Front.jpg 
2020-05-04T06:49:45-04:00 [ampache] (art.class) -> gather_folder: Found image file: Christine Santelli - Any Better Time - CD.jpg 
2020-05-04T06:49:45-04:00 [ampache] (art.class) -> gather_folder: Results: {"bb75419551d402b7318044af43f4688d":{"file":"\/home\/...\/Music\/My Music\/Christine Santelli\/Any Better Time\/Christine Santelli - Any Better Time - Inside.jpg","mime":"image\/jpeg","title":"Folder"},"f41c4093fb6c7c3dc7e48a09f0f9ec5b":{"file":"\/home\/...\/Music\/My Music\/Christine Santelli\/Any Better Time\/Christine Santelli - Any Better Time - Front.jpg","mime":"image\/jpeg","title":"Folder"},"37da48930f2eaf0b3aa6ecbc282f5634":{"file":"\/home\/...\/Music\/My Music\/Christine Santelli\/Any Better Time\/Christine Santelli - Any Better Time - CD.jpg","mime":"image\/jpeg","title":"Folder"}} 
2020-05-04T06:49:45-04:00 [ampache] (art.class) -> Method used: gather_musicbrainz 
2020-05-04T06:49:45-04:00 [ampache] (art.class) -> gather_musicbrainz Album MBID: b027b712-dbd7-4a0d-9c55-c3643e4ff0ec 
2020-05-04T06:49:46-04:00 [ampache] (art.class) -> gather_musicbrainz Found URL AR: http://christinesantelli.com/store 
2020-05-04T06:49:46-04:00 [ampache] (art.class) -> Method used: gather_lastfm 
2020-05-04T06:49:46-04:00 [ampache] (recommendation.class) -> search url : http://ws.audioscrobbler.com/2.0/?method=album.getInfo&artist=Christine+Santelli&album=Any+Better+Time&api_key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx 
2020-05-04T06:49:47-04:00 [ampache] (art.class) -> LastFM: Detected as noimage, skipped Array 
2020-05-04T06:49:47-04:00 [ampache] (theaudiodb.plugin) -> gather_arts for type `album` 
2020-05-04T06:49:47-04:00 [ampache] (theaudiodb.plugin) -> Getting album metadata from TheAudioDb... 
2020-05-04T06:49:47-04:00 [ampache] (theaudiodb.plugin) -> API call: http://www.theaudiodb.com/api/v1/json/xxxxxxxxxxxxxxxxxxxx/album-mb.php?i=d604af73-d384-4920-846f-10f21a109529 
2020-05-04T06:49:48-04:00 [ampache] (discogs.plugin) -> Getting metadata from Discogs... 
2020-05-04T06:49:48-04:00 [ampache] (discogs.plugin) -> Discogs request: https://api.discogs.com/database/search?type=master&release_title=Any%20Better%20Time&artist=Christine%20Santelli&per_page=10&key=xxxxxxxxxxxxxxxxxxxxx&secret=xxxxxxxxxxxxxxxxxxxxxxxxxxxx 
2020-05-04T06:49:48-04:00 [ampache] (log.lib) -> [Runtime Error] count(): Parameter must be an array or an object that implements Countable in file /var/www/ampache/modules/plugins/Discogs/Discogs.plugin.php(201) 
2020-05-04T06:49:48-04:00 [ampache] (amazonsearchengine.class) -> Retrieving from 2d656564694f234d656564/onca/xml 
2020-05-04T06:49:48-04:00 [ampache] (amazonsearchengine.class) -> Amazon request: http://2d656564694f234d656564/onca/xml?AWSAccessKeyId=xxxxxxxxxxxxxxxxxxxxxxx&Artist=&AssociateTag=xxxxxxxxxxxxxxxxxxxxxx&Keywords=%20Christine%20Santelli%20Any%20Better%20Time&Operation=ItemSearch&SearchIndex=Music&Service=AWSECommerceService&Timestamp=2020-05-04T10%3A49%3A48Z&Title=&Version=2009-03-31&Signature=cD1t%2FMoWNm1yWUVTGNg0FGtqgxWMTiw8yO8Cf9y8oM4%3D 
 


```

**Comment by lachlan-00** [comment]
looks like it's moved to json only now.

I'll have to sign up for this gateway thing to see how it all works.
https://docs.aws.amazon.com/apigateway/latest/developerguide/getting-started.html

**Comment by lachlan-00** [comment]
fixed the discogs runtime error for now at least

**Comment by stebe** [comment]
I'm going to add this to the issue too, I can move to a new issue if you think it warrants one. When the script is running "- Update artist information and fetch similar artists from last.fm - " I'm seeing this error in the debug log.

```
2020-05-05T08:51:15-04:00 [ampache] (recommendation.class) -> search url : http://ws.audioscrobbler.com/2.0/?method=artist.getinfo&api_key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&artist=&lang=en 
2020-05-05T08:51:15-04:00 [ampache] (recommendation.class) -> search url : http://ws.audioscrobbler.com/2.0/?method=artist.getsimilar&api_key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&artist=&lang=en 
2020-05-05T08:51:15-04:00 [ampache] (log.lib) -> [Runtime Error] Recommendation::get_artists_like(): Node no longer exists in file /var/www/ampache/lib/class/recommendation.class.php(271)
```

**Comment by lachlan-00** [comment]
simplexml error when xml is empty?

```
@return SimpleXMLElement a <b>SimpleXMLElement</b> element, whether the node
	 * has children or not.
```

i'll see if i can print the xml on an error but i would guess that's there are no children

**Comment by stebe** [comment]
No need to print the xml. I am curious if this should be logged as a runtime error, when it really isn't an error.

**Comment by lachlan-00** [comment]
i think it's a php error where the xml isn't getting the data.to continue

like if:
 * you search for x-band
 * but it doesn't exist
 * return x-band-()     (no details)
 * error because you didn't find children for the band node
