### ISSUE TITLE
id3 error when doing add on Video

### ISSUE THREAD

**Issue by stebe** [ampache/ampache#2616]
### Describe the bug

I'm getting SQL errors when doing an add in a video catalog.

* Ampache version: d6e2b9b1670bb8a4207b3a04b282576045ad94c8

## Logs

```


2020-11-12T18:15:40-05:00 [stebe] (local.catalog) -> Reading Viewed inside /home/steve/Media/anime 
2020-11-12T18:15:40-05:00 [stebe] (local.catalog) -> Memory usage: 14 MB 
2020-11-12T18:15:40-05:00 [stebe] (dba.class) -> Error_query SQL: INSERT INTO `video` (`file`, `catalog`, `title`, `video_codec`, `audio_codec`, `resolution_x`, `resolution_y`, `size`, `time`, `mime`, `release_date`, `addition_time`, `bitrate`, `mode`, `channels`, `display_x`, `display_y`, `frame_rate`, `video_bitrate`)  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) 
2020-11-12T18:15:40-05:00 [stebe] (dba.class) -> Error_query MSG: ["22003",1264,"Out of range value for column 'video_bitrate' at row 1"] 
2020-11-12T18:15:40-05:00 [stebe] (dba.class) -> Error_query SQL: INSERT INTO `video` (`file`, `catalog`, `title`, `video_codec`, `audio_codec`, `resolution_x`, `resolution_y`, `size`, `time`, `mime`, `release_date`, `addition_time`, `bitrate`, `mode`, `channels`, `display_x`, `display_y`, `frame_rate`, `video_bitrate`)  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) 
2020-11-12T18:15:40-05:00 [stebe] (dba.class) -> Error_query MSG: ["22003",1264,"Out of range value for column 'video_bitrate' at row 1"] 
2020-11-12T18:15:40-05:00 [stebe] (dba.class) -> Error_query SQL: INSERT INTO `video` (`file`, `catalog`, `title`, `video_codec`, `audio_codec`, `resolution_x`, `resolution_y`, `size`, `time`, `mime`, `release_date`, `addition_time`, `bitrate`, `mode`, `channels`, `display_x`, `display_y`, `frame_rate`, `video_bitrate`)  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) 
2020-11-12T18:15:40-05:00 [stebe] (dba.class) -> Error_query MSG: ["22003",1264,"Out of range value for column 'video_bitrate' at row 1"] 
2020-11-12T18:15:40-05:00 [stebe] (dba.class) -> Error_query SQL: INSERT INTO `video` (`file`, `catalog`, `title`, `video_codec`, `audio_codec`, `resolution_x`, `resolution_y`, `size`, `time`, `mime`, `release_date`, `addition_time`, `bitrate`, `mode`, `channels`, `display_x`, `display_y`, `frame_rate`, `video_bitrate`)  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) 
2020-11-12T18:15:40-05:00 [stebe] (dba.class) -> Error_query MSG: ["22003",1264,"Out of range value for column 'video_bitrate' at row 1"] 
2020-11-12T18:15:40-05:00 [stebe] (dba.class) -> Error_query SQL: INSERT INTO `personal_video` (`id`, `location`, `summary`) VALUES (?, ?, ?) 
2020-11-12T18:15:40-05:00 [stebe] (dba.class) -> Error_query MSG: ["23000",1062,"Duplicate entry '0' for key 'PRIMARY'"] 
2020-11-12T18:15:40-05:00 [stebe] (dba.class) -> Error_query SQL: INSERT INTO `personal_video` (`id`, `location`, `summary`) VALUES (?, ?, ?) 
2020-11-12T18:15:40-05:00 [stebe] (dba.class) -> Error_query MSG: ["23000",1062,"Duplicate entry '0' for key 'PRIMARY'"] 
2020-11-12T18:15:40-05:00 [stebe] (dba.class) -> Error_query SQL: INSERT INTO `personal_video` (`id`, `location`, `summary`) VALUES (?, ?, ?) 
2020-11-12T18:15:40-05:00 [stebe] (dba.class) -> Error_query MSG: ["23000",1062,"Duplicate entry '0' for key 'PRIMARY'"] 
2020-11-12T18:15:40-05:00 [stebe] (dba.class) -> Error_query SQL: INSERT INTO `personal_video` (`id`, `location`, `summary`) VALUES (?, ?, ?) 
2020-11-12T18:15:40-05:00 [stebe] (dba.class) -> Error_query MSG: ["23000",1062,"Duplicate entry '0' for key 'PRIMARY'"] 
2020-11-12T18:15:40-05:00 [stebe] (vainfo.class) -> Unable to determine file type from h264 on file /home/steve/Media/anime/Viewed/Fate Stay Night/Fate Stay Night - Unlimited Blade Works/[Hatsuyuki]_Fate_stay_night_-_Unlimited_Blade_Works_-_PV1_[BD][1280x720][DC5AA785].mkv 
2020-11-12T18:15:40-05:00 [stebe] (vainfo.class) -> Cleaning matroska 
2020-11-12T18:15:40-05:00 [stebe] (dba.class) -> Error_query SQL: INSERT INTO `video` (`file`, `catalog`, `title`, `video_codec`, `audio_codec`, `resolution_x`, `resolution_y`, `size`, `time`, `mime`, `release_date`, `addition_time`, `bitrate`, `mode`, `channels`, `display_x`, `display_y`, `frame_rate`, `video_bitrate`)  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) 
2020-11-12T18:15:40-05:00 [stebe] (dba.class) -> Error_query MSG: ["22003",1264,"Out of range value for column 'video_bitrate' at row 1"] 
2020-11-12T18:15:40-05:00 [stebe] (dba.class) -> Error_query SQL: INSERT INTO `video` (`file`, `catalog`, `title`, `video_codec`, `audio_codec`, `resolution_x`, `resolution_y`, `size`, `time`, `mime`, `release_date`, `addition_time`, `bitrate`, `mode`, `channels`, `display_x`, `display_y`, `frame_rate`, `video_bitrate`)  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) 
2020-11-12T18:15:40-05:00 [stebe] (dba.class) -> Error_query MSG: ["22003",1264,"Out of range value for column 'video_bitrate' at row 1"] 
2020-11-12T18:15:40-05:00 [stebe] (dba.class) -> Error_query SQL: INSERT INTO `video` (`file`, `catalog`, `title`, `video_codec`, `audio_codec`, `resolution_x`, `resolution_y`, `size`, `time`, `mime`, `release_date`, `addition_time`, `bitrate`, `mode`, `channels`, `display_x`, `display_y`, `frame_rate`, `video_bitrate`)  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) 
2020-11-12T18:15:40-05:00 [stebe] (dba.class) -> Error_query MSG: ["22003",1264,"Out of range value for column 'video_bitrate' at row 1"] 
2020-11-12T18:15:40-05:00 [stebe] (dba.class) -> Error_query SQL: INSERT INTO `video` (`file`, `catalog`, `title`, `video_codec`, `audio_codec`, `resolution_x`, `resolution_y`, `size`, `time`, `mime`, `release_date`, `addition_time`, `bitrate`, `mode`, `channels`, `display_x`, `display_y`, `frame_rate`, `video_bitrate`)  VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) 
2020-11-12T18:15:40-05:00 [stebe] (dba.class) -> Error_query MSG: ["22003",1264,"Out of range value for column 'video_bitrate' at row 1"] 
2020-11-12T18:15:40-05:00 [stebe] (dba.class) -> Error_query SQL: INSERT INTO `personal_video` (`id`, `location`, `summary`) VALUES (?, ?, ?) 
2020-11-12T18:15:40-05:00 [stebe] (dba.class) -> Error_query MSG: ["23000",1062,"Duplicate entry '0' for key 'PRIMARY'"] 
2020-11-12T18:15:40-05:00 [stebe] (dba.class) -> Error_query SQL: INSERT INTO `personal_video` (`id`, `location`, `summary`) VALUES (?, ?, ?) 
2020-11-12T18:15:40-05:00 [stebe] (dba.class) -> Error_query MSG: ["23000",1062,"Duplicate entry '0' for key 'PRIMARY'"] 
2020-11-12T18:15:40-05:00 [stebe] (dba.class) -> Error_query SQL: INSERT INTO `personal_video` (`id`, `location`, `summary`) VALUES (?, ?, ?) 
2020-11-12T18:15:40-05:00 [stebe] (dba.class) -> Error_query MSG: ["23000",1062,"Duplicate entry '0' for key 'PRIMARY'"] 
2020-11-12T18:15:40-05:00 [stebe] (dba.class) -> Error_query SQL: INSERT INTO `personal_video` (`id`, `location`, `summary`) VALUES (?, ?, ?) 
2020-11-12T18:15:40-05:00 [stebe] (dba.class) -> Error_query MSG: ["23000",1062,"Duplicate entry '0' for key 'PRIMARY'"] 
```

**Comment by wagnered** [comment]
H264 is not included on the getID3 home page and .mkv

**Comment by lachlan-00** [comment]
it's not creating the id so it fails. the 0 is a null cast to int
```
"Out of range value for column 'video_bitrate' at row 1"
```
i'll check the bitrate column but it shouldn't be so low that it needs to be extended.

**Comment by lachlan-00** [comment]
max length is pretty big so it must be a large video or this is read in bytes instead of kilobytes?
8,388,607

**Comment by lachlan-00** [comment]
707c04baa adds a check for the ints (4294967294 max, 0 min unsigned DB update)

It seems to be in bytes so the should cover a lot of videos now.

It'll be a good thing to start setting checks for other ints in the database like this.

**Comment by stebe** [comment]
@wagnered there is only one file like that so I'm not too concerned.  I may just rename it mp4 and solve it that way.

@lachlan-00 the errors are now gone, but the database update had failed for me.  There was one row with a negative video bitrate for some reason.  I just set that bitrate to null for that row and the database update was successful. The updatedb page never showed the error, just kept returning to the update database button, only the logs showed the error.   Perhaps there should be a message when the database update fails and to check the logs. I'll open a feature request for this.

**Comment by lachlan-00** [comment]
I'll need to partly revert that in a new update instead with a 0 first.

**Comment by stebe** [comment]
I'm not sure if this is related.  The database errors are gone but the catalog doesn't complete the add.  I get this error in the log when video catalog add is run.

```
2020-11-13T05:53:05-05:00 [admin] (local.catalog) -> Reading Viewed inside /home/steve/Media/anime 
2020-11-13T05:53:05-05:00 [admin] (local.catalog) -> Memory usage: 2 MB 
2020-11-13T05:53:05-05:00 [admin] (core.class) -> 'Dts' not found!
```

**Comment by lachlan-00** [comment]
I'll add my video folder and have a look. The examples I keep don't even report a bitrate so I'll need more

**Comment by lachlan-00** [comment]
@wagnered this error above seems to be where the new id3 tag code is trying to read the video and failing
```
[Sun Nov 15 10:36:09.637168 2020] [proxy_fcgi:error] [pid 1440385:tid 139675143018240] [client 192.168.1.9:51354] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Class 'Ac3' not found in /var/www/music/lib/vendor/james-heinrich/getid3/src/Module/AudioVideo/Matroska.php:381\nStack trace:\n#0 /var/www/music/lib/vendor/james-heinrich/getid3/src/GetID3.php(483): JamesHeinrich\\GetID3\\Module\\AudioVideo\\Matroska->Analyze()\n#1 /var/www/music/lib/class/vainfo.class.php(113): JamesHeinrich\\GetID3\\GetID3->analyze()\n#2 /var/www/music/modules/catalog/local/local.catalog.php(892): vainfo->__construct()\n#3 /var/www/music/modules/catalog/local/local.catalog.php(438): Catalog_local->insert_local_video()\n#4 /var/www/music/modules/catalog/local/local.catalog.php(295): Catalog_local->add_file()\n#5 /var/www/music/modules/catalog/local/local.catalog.php(506): Catalog_local->add_files()\n#6 /var/www/music/lib/class/catalog.class.php(2883): Catalog_local->add_to_catalog()\n#7 /var/www/music/server/sse.server.php(69): Catalog::process_action()\n#8 {main}\n  thrown in /var/www/music/lib/vendor/james-heinrich/getid3/src/Module/AudioVideo/Matr...', referer: https://music.com.au/index.php
```

In the UI it causes a loop by restarting the add each time it fails.

**Comment by wagnered** [comment]
AC3 is the audio format, what is the video format? Matroska is the container.   Need to find a similar file to step through.  I'll see if I can find a CC licensed mkv file somewhere.

**Comment by wagnered** [comment]
Interestig !!  Used ffmpeg to convert an mp4 to  an mkv container file with ac3 audio. There is an Ac3 class.  It has a namespace and the matroska file is using the namespace.  Maybe not correctly.

**Comment by wagnered** [comment]
To get 'past the error you refer to, I had to prepend the entire namespace to the variable `$class`.  This is in accord with the php.net document ation.

But it's back to the h264 problem:
> Unable to determine file type from h264 on file ...

Also getting the *out of range for column video_bitrate".

**Comment by wagnered** [comment]
The h264 complaint from vainfo::_clean_type($type) is because there is no relationship between the audio/video and the mkv container.

I'll revert the getID3 library and let James Heinrich know about the bug.

**Comment by lachlan-00** [comment]
reverted commits from 3456b0667 work for video now. There's only one odd issue left...
```
(song.class) -> media-diff {"disk":"OLD:1 --> "}
```
![image](https://user-images.githubusercontent.com/1305249/99217667-58e0e700-2824-11eb-85d0-0ea5a2e7a708.png)

**Comment by lachlan-00** [comment]
it's not parsing disk tags apparently
```
2020-11-16T16:17:39+10:00 [user] (vainfo.class) -> id3v2 tag: title value: Winter Ade 
2020-11-16T16:17:39+10:00 [user] (vainfo.class) -> id3v2 tag: artist value: Ost+Front 
2020-11-16T16:17:39+10:00 [user] (vainfo.class) -> id3v2 tag: band value: Ost+Front 
2020-11-16T16:17:39+10:00 [user] (vainfo.class) -> id3v2 tag: album value: Liebeslied 
2020-11-16T16:17:39+10:00 [user] (vainfo.class) -> id3v2 tag: track_number value: 2 
2020-11-16T16:17:39+10:00 [user] (vainfo.class) -> id3v2 tag: part_of_a_set value: 1/1 
2020-11-16T16:17:39+10:00 [user] (vainfo.class) -> id3v2 tag: recording_time value: 2014-01-03 
2020-11-16T16:17:39+10:00 [user] (vainfo.class) -> id3v2 tag: genre value: Rock 
2020-11-16T16:17:39+10:00 [user] (vainfo.class) -> id3v2 tag: bpm value: 96 
2020-11-16T16:17:39+10:00 [user] (vainfo.class) -> id3v2 tag: publisher value: Out of Line 
2020-11-16T16:17:39+10:00 [user] (vainfo.class) -> id3v2 tag: performer_sort_order value: Ost+Front 
2020-11-16T16:17:39+10:00 [user] (vainfo.class) -> id3v2 tag: file_type value: MPG/3 
2020-11-16T16:17:39+10:00 [user] (vainfo.class) -> id3v2 tag: tagging_time value: 2014-09-24T03:37:28 
2020-11-16T16:17:39+10:00 [user] (vainfo.class) -> id3v2 tag: original_release_time value: 2014-01-03 
2020-11-16T16:17:39+10:00 [user] (vainfo.class) -> id3v2 tag: album_artist_sort_order value: Ost+Front 
2020-11-16T16:17:39+10:00 [user] (vainfo.class) -> id3v2 tag: media_type value: 7" Vinyl 
2020-11-16T16:17:39+10:00 [user] (vainfo.class) -> id3v2 tag: text value:  
2020-11-16T16:17:39+10:00 [user] (vainfo.class) -> id3v2 tag: terms_of_use value: yright notice. These materials are protected by United States copyright law and by international treaties. You may use these materials for your personal, non-commercial use only. You may not otherwise reproduce, distribute, publicly perform, publicly display, or create derivative works of these materials, unless authorized by the appropriate copyright owner(s). 
2020-11-16T16:17:39+10:00 [user] (vainfo.class) -> id3v2 tag: totaltracks value: 2 
2020-11-16T16:17:39+10:00 [user] (vainfo.class) -> id3v2 tag: year value: 2014
```

**Comment by lachlan-00** [comment]
scratch that, disk is an album property so it shouldn't be updated here.
fixed that in 8695f0c25 so i think this is okay again. i'll just check we aren't comparing more properties

**Comment by stebe** [comment]
With commit 4ab831c406e2dc9351a7ae849a2607fd98123e13 video add appears to be working now.  I'm finding new videos and art is created.

**Comment by lachlan-00** [comment]
that's good, i didn't I'm unsure why disk properties where being checked in the reversion but i'll be double checking those today.

will need to include the video libraries in my testing again later
