### ISSUE TITLE
catalog_update.inc failing to add new content to database

### ISSUE THREAD

**Issue by tim-e-de-vries** [ampache/ampache#2619]
## Description
Cannot add new content to Ampache database using catalog_update.inc script
### Describe the bug

Trying to add new music content to my installation and it keeps failing
### To reproduce
Command to launch catalog_update.inc:

```
sudo -u www-data /bin/bash -c "php /var/www/html/ampache/bin/catalog_update.inc -m -a -g -u -o > /var/log/ampache/catalog_update.log 2>&1
```
. See error in catalog_update.log file
```
----------------------------------------------------------
Starting Catalog operations...
        - Temporarily deactivating PHP memory limit
        - Adding new media to Catalog/s
----------------------------------------------------------

- Deactivated PHP memory limit -
------------------

PHP Fatal error:  Uncaught Error: Class 'JamesHeinrich\GetID3\GetID3' not found in /var/www/html/ampache/lib/class/vainfo.class.php:100
Stack trace:
#0 /var/www/html/ampache/modules/catalog/local/local.catalog.php(775): vainfo->__construct()
#1 /var/www/html/ampache/modules/catalog/local/local.catalog.php(429): Catalog_local->insert_local_song()
#2 /var/www/html/ampache/modules/catalog/local/local.catalog.php(295): Catalog_local->add_file()
#3 /var/www/html/ampache/modules/catalog/local/local.catalog.php(348): Catalog_local->add_files()
#4 /var/www/html/ampache/modules/catalog/local/local.catalog.php(295): Catalog_local->add_file()
#5 /var/www/html/ampache/modules/catalog/local/local.catalog.php(348): Catalog_local->add_files()
#6 /var/www/html/ampache/modules/catalog/local/local.catalog.php(295): Catalog_local->add_file()
#7 /var/www/html/ampache/modules/catalog/local/local.catalog.php(348): Catalog_local->add_files()
#8 /var/www/html/ampache/modules/catalog/local/local.catalog.php(295): Catalog_local->add_file()
#9 /var/www/ in /var/www/html/ampache/lib/class/vainfo.class.php on line 100
Reading Catalog: "Music"
- Start adding new media - 
           Starting New Media Search
Starting New Media Search on "[ Music ]" Catalog
Found: None
Reading:
```

## Environment

* Ampache version:   Installed Ampache version: 707c04baae80560e2121a85b71087899e96398cc.
* Web server + version:  Apache  
* Server operating system:  Ubuntu Linux

## Logs
Relevant portion of log file
```
2020-11-13T21:15:41-05:00 [ampache] (catalog.class) -> clean finished, 13 removed from Music
2020-11-13T21:15:42-05:00 [ampache] (local.catalog) -> Verify starting on Music
2020-11-13T21:15:42-05:00 [ampache] (local.catalog) -> Verify starting chunk 0
2020-11-13T21:15:42-05:00 [ampache] (local.catalog) -> Verify starting chunk 1
2020-11-13T21:15:42-05:00 [ampache] (local.catalog) -> Verify starting chunk 2
2020-11-13T21:15:42-05:00 [ampache] (local.catalog) -> Verify starting chunk 0
2020-11-13T21:15:42-05:00 [ampache] (core.class) -> 'JamesHeinrich\GetID3\GetID3' not found!
2020-11-13T21:15:42-05:00 [ampache] (core.class) -> 'JamesHeinrich\GetID3\GetID3' not found!
```

**Comment by wagnered** [comment]
Running `composer update` should take care of the problem. The getID3 library has been upgraded.  I forgot to add it to the change log.

**Comment by tim-e-de-vries** [comment]
Yep.  That fixed it.  Thank you!!!!
