### ISSUE TITLE
Cannot add a new catalog, PHP Fatal error:  Uncaught ValueError: mb_convert_encoding(): Argument #3 ($from_encoding) must specify at least one encoding in /usr/share/webapps/ampache/lib/vendor/james-heinrich/getid3/getid3/getid3.lib.php:1230

### ISSUE THREAD

**Issue by BoBeR182** [ampache/ampache#2762]
# Issue Template

## Description

**Describe the bug**
Cannot add catalog

**To reproduce**
1. Try to add a new catalog

**Expected behavior**
Get more music

**Screenshots**

## Environment

* Ampache version:
* Web server + version:
* Server operating system:
* Client operating system:

**Client type:**

* Web

## Logs

```
[Thu Feb 18 22:41:23.728429 2021] [php:error] [pid 1532585] [client ::1:49236] PHP Fatal error:  Uncaught ValueError: mb_convert_encoding(): Argument #3 ($from_encoding) must specify at least one encoding in /usr/share/webapps/ampache/lib/vendor/james-heinrich/getid3/getid3/getid3.lib.php:1230\nStack trace:\n#0 /usr/share/webapps/ampache/lib/vendor/james-heinrich/getid3/getid3/getid3.lib.php(1230): mb_convert_encoding()\n#1 /usr/share/webapps/ampache/lib/vendor/james-heinrich/getid3/getid3/getid3.php(1444): getid3_lib::iconv_fallback()\n#2 /usr/share/webapps/ampache/lib/vendor/james-heinrich/getid3/getid3/getid3.php(1439): getID3->CharConvert()\n#3 /usr/share/webapps/ampache/lib/vendor/james-heinrich/getid3/getid3/getid3.php(1517): getID3->CharConvert()\n#4 /usr/share/webapps/ampache/lib/vendor/james-heinrich/getid3/getid3/getid3.php(644): getID3->HandleAllTags()\n#5 /usr/share/webapps/ampache/lib/class/vainfo.class.php(230): getID3->analyze()\n#6 /usr/share/webapps/ampache/modules/catalog/local/local.catalog.php(776): vainfo->get_info()\n#7 /usr/share/webapps/ampache/modules/catalog/local/local.catalog.php(429): Catalog_local->insert_local_song()\n#8 /usr/share/webapps/ampache/modules/catalog/local/local.catalog.php(295): Catalog_local->add_file()\n#9 /usr/share/webapps/ampache/modules/catalog/local/local.catalog.php(348): Catalog_local->add_files()\n#10 /usr/share/webapps/ampache/modules/catalog/local/local.catalog.php(295): Catalog_local->add_file()\n#11 /usr/share/webapps/ampache/modules/catalog/local/local.catalog.php(506): Catalog_local->add_files()\n#12 /usr/share/webapps/ampache/lib/class/catalog.class.php(2801): Catalog_local->add_to_catalog()\n#13 /usr/share/webapps/ampache/server/sse.server.php(68): Catalog::process_action()\n#14 {main}\n  thrown in /usr/share/webapps/ampache/lib/vendor/james-heinrich/getid3/getid3/getid3.lib.php on line 1230

```

**Comment by lachlan-00** [comment]
does the error come up using the command line add?

**Comment by wagnered** [comment]
@BoBeR182 

Looking at the error and  code, it appears that getID3 was trying to process an unrecognized file (wma?), although i'm not sure the logic would allow a file of a type that isn't listed in the `getid3_tag_order ` config switch. I tried both 4.25 and 4.3 with no problem adding catalog and content.

**Comment by BoBeR182** [comment]
`sudo -u http php -f ./bin/catalog_update.inc `
```
----------------------------------------------------------
Starting Catalog operations...
	- Doing all Catalog operations
----------------------------------------------------------

Reading Catalog: "music"
- Start cleaning orphaned media entries - 
           Clean Catalog
Cleaning the "[ music ]" Catalog...
Checking: 
Reading: 
1
/media/Storage/music/Arcade Fire - Funeral [2004]WEB-FLAC-Lossless/02 - Neighborhood #2 Laika.flac
0 files removed.------------------
- Start verifying media related to Catalog entries - 
           Verify Catalog
Updating the [ music ] Catalog
Verified: 
Reading:     
0
11
11 files updated.PHP Fatal error:  Uncaught ValueError: mb_convert_encoding(): Argument #3 ($from_encoding) must specify at least one encoding in /usr/share/webapps/ampache/lib/vendor/james-heinrich/getid3/getid3/getid3.lib.php:1230
Stack trace:
#0 /usr/share/webapps/ampache/lib/vendor/james-heinrich/getid3/getid3/getid3.lib.php(1230): mb_convert_encoding()
#1 /usr/share/webapps/ampache/lib/vendor/james-heinrich/getid3/getid3/getid3.php(1444): getid3_lib::iconv_fallback()
#2 /usr/share/webapps/ampache/lib/vendor/james-heinrich/getid3/getid3/getid3.php(1439): getID3->CharConvert()
#3 /usr/share/webapps/ampache/lib/vendor/james-heinrich/getid3/getid3/getid3.php(1517): getID3->CharConvert()
#4 /usr/share/webapps/ampache/lib/vendor/james-heinrich/getid3/getid3/getid3.php(644): getID3->HandleAllTags()
#5 /usr/share/webapps/ampache/lib/class/vainfo.class.php(230): getID3->analyze()
#6 /usr/share/webapps/ampache/modules/catalog/local/local.catalog.php(776): vainfo->get_info()
#7 /usr/share/webapps/ampache/modules/catalog/local/local.catalog.php(429): Catalog_local->insert_local_song()
#8 /usr/share/webapps/ampache/modules/catalog/local/local.catalog.php(295): Catalog_local->add_file()
#9 /usr/share/webapps/ampache/modules/catalog/local/local.catalog.php(348): Catalog_local->add_files()
#10 /usr/share/webapps/ampache/modules/catalog/local/local.catalog.php(295): Catalog_local->add_file()
#11 /usr/share/webapps/ampache/modules/catalog/local/local.catalog.php(506): Catalog_local->add_files()
#12 /usr/share/webapps/ampache/bin/catalog_update.inc(171): Catalog_local->add_to_catalog()
#13 {main}
  thrown in /usr/share/webapps/ampache/lib/vendor/james-heinrich/getid3/getid3/getid3.lib.php on line 1230
-------------------
- Start adding new media - 
           Starting New Media Search
Starting New Media Search on "[ music ]" Catalog
Found: None
Reading:%    ```

**Comment by wagnered** [comment]
@BoBeR182   thank you for the additional info. I'm not sure how well Ampache has been tested with php8.*.  Do you have the mbstring and iconv extensions enabled?  Would it be possible for you to revert to php7.1 to php7.4? and give it a try. 

@usox  Has Ampache 4.*.* been fully tested with php8.*?  The wiki says php 7.1 or greater is required, but does that include php8?  Maybe Composer notation should be used (^7.1) ;'>

I'll install php and attempt to confirm this specific issue.

**Comment by usox** [comment]
@wagnered I'm quite sure nobody has tested ampache (4.x / 5.x) in php8 yet. In source-changes, I tested the composer dependency installation - but not the functionality. Pinning the php requirement in 4.x to 7.x could be a good idea.

It would be good to know, if <php8 fails with the file, too. Maybe getid3 actually fails to detect the encoding which may cause the error (track name for example "Laïka") - regardless of the version.

**Comment by BoBeR182** [comment]
`php -m`
```
[PHP Modules]
apcu
bcmath
bz2
Core
ctype
curl
date
dom
fileinfo
filter
gd
gettext
hash
iconv
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
SimpleXML
soap
SPL
standard
tokenizer
xml
xmlreader
xmlwriter
zip
zlib

[Zend Modules]
```

I don't have the ability to downgrade PHP to 7

**Comment by wagnered** [comment]
ouch!  I installed the release from ampache-4.2.5_all.zip and it wouldn't run. Got a fatal error right off.

>  I don't have the ability to downgrade PHP to 7

This implies that the server is hosted.  Perhaps the system manager needs to install `libiconv` library on the host.  
```
PHP Fatal error:  Uncaught ValueError: mb_convert_encoding(): Argument #3 ($from_encoding) must specify at least one encoding in /usr/share/webapps/ampache/lib/vendor/james-heinrich/getid3/getid3/getid3.lib.php:1230
Stack trace:
```

So, if you are sure that you are running php8.0.2, then php8.* might have a bug because the specs indicates that the third argument can be null (absent) in 8.02.

The last possibility is that an unsupported encoding is being passed, from the FLAC file but without those exact files, the issue cannot be duplicated. Too bad the file info above, doesn't iinclude the encoding.

FYI I installed the Apache 4.2.5 source and was able to import my .FLAC files into the catalog but many more errors were recorded. This also reqires that composer be installed on the system.

**Comment by BoBeR182** [comment]
![image](https://user-images.githubusercontent.com/525433/108662740-dae94780-74c6-11eb-8637-7e1e9f4395c3.png)

I'm sure I'm on PHP8, and yes it was a rolling release update. I am using Arch Linux.
I can upload the FLAC that shows up in the error if you would like, but I'd prefer to distribute it privately due to the copyright status of it. Would you have a preferred method of contacting you to share the file in question?

**Comment by wagnered** [comment]
> you have a preferred method of contacting you to share the file in question?

Only one file gives you the problem?  If so, then it's probably the file is damaged.

if you have a problem file less than 20 mb , at comcast's suggestion (there is about a 5 mb overhead required),  my email address is on my profile page.

**Comment by BoBeR182** [comment]
Never mind that, I removed the file in question and reran the command from CLI, still shows same error, and holds up on other files. Seems unrelated. Nothing gets added to the catalog.

**Comment by wagnered** [comment]
First i want to ask if there was a problem with other types of files, like mp3?

Also, php-8.0 was released only a few months ago (Nov 2020). I'm surprised the system manager upgraded so quickly.  Sorry to say that  the milestone for Ampache with php-8 appears to be V5.1.

**Comment by BoBeR182** [comment]
No files get imported, even MP3 only catalogs.
Sadly I guess I will look at downgrading to PHP7.4 or waiting for a PHP8 release.
As usual I blame Arch Linux
