### ISSUE TITLE
cli: admin:updateDatabase does not work in 5.0.0

### ISSUE THREAD

**Issue by gramakri** [ampache/ampache#3019]
### Describe the bug
I am updating the Cloudron Ampache package from 4.4.3 to 5.0.0. To run the database migrations, I use `bin/cli admin:updateDatabase`. However, this command throws an exception.

### To reproduce

1. Staring with ampache 4.4.3.
2. Update code to ampache 5.0.0
3. Run `bin/cli admin:updataDatabase`

```
# /app/code/bin/cli admin:updateDatabase 
PHP Fatal error:  Uncaught Ampache\Config\Init\Exception\DatabaseOutdatedException: Database outdated - please update in /app/code/src/Config/Init/InitializationHandlerDatabaseUpdate.php:37
Stack trace:
#0 /app/code/src/Config/Init/Init.php(58): Ampache\Config\Init\InitializationHandlerDatabaseUpdate->init()
#1 /app/code/src/Config/Init.php(37): Ampache\Config\Init\Init->init()
#2 /app/code/bin/cli(34): require('/app/code/src/C...')
#3 {main}
  thrown in /app/code/src/Config/Init/InitializationHandlerDatabaseUpdate.php on line 37
```

### Expected behavior
The list of database migrations should be listed. When `--execute` is passed, the migrations should be run as well.

**Comment by gramakri** [comment]
The issue here is that the CLI calls Init->init() which in turn inits the DatabaseUpdate module, which throws an outdated exception. It's a catch-22 because the goal of the admin:updateDatabase command is to update the database.

As a quick hack, I put in `define('OUTDATED_DATABASE_OK', 1);` in bin/cli and re-ran the command, and it worked:

```
# /app/code/bin/cli admin:updateDatabase --execute

The following updates need to be performed:
Version: 5.0 Build:0003
* Create catalog_map table and fill it with data
Version: 5.0 Build:0004
**IMPORTANT UPDATE NOTES**<br />For large catalogs this will be slow!<br />* Create catalog_map table and fill it with data
Version: 5.0 Build:0005
* Add song_count, artist_count to album
Version: 5.0 Build:0006
* Add user_playlist and user_data table
Version: 5.0 Build:0007
* Add a 'Browse' category to interface preferences<br />* Add option ('show_license') for hiding license column in song rows
Version: 5.0 Build:0008
* Add filter_user to catalog table<br />* Set a unique key on user_data
Version: 5.0 Build:0009
* Add ui option ('use_original_year') Browse by Original Year for albums (falls back to Year)
Version: 5.0 Build:0010
* Add ui option ('hide_single_artist') Hide the Song Artist column for Albums with one Artist
Version: 5.0 Build:0011
* Add `total_count` to podcast table and fill counts into the column
Version: 5.0 Build:0012
* Move user bandwidth calculations out of the user format function into the user_data table
Version: 5.0 Build:0013
* Add tables for tracking deleted files. (deleted_song, deleted_video, deleted_podcast_episode)<br />* Add username to the playlist table to stop pulling user all the time
Version: 5.0 Build:0014
* Add `episodes` to podcast table to track episode count
Version: 5.0 Build:0015
* Add ui option ('hide_genres') Hide the Genre column in browse table rows
```

I guess we need to define OUTDATED_DATABASE_OK somewhere, but I don't know Ampache code well enough as to where it goes.

**Comment by lachlan-00** [comment]
i've put the OUTDATED_DATABASE_OK in the code for develop now

@basti0001 this will skip 5005 for you
```
UPDATE update_info SET value='update_500005' WHERE `key`='db_version';
```

can you try all these (separately) too to see what the issue was. if they work fine the issue was something else
```
UPDATE `album`, (SELECT COUNT(`song`.`id`) AS `song_count`, `album` FROM `song` LEFT JOIN `catalog` ON `catalog`.`id` = `song`.`catalog` WHERE `catalog`.`enabled` = '1' GROUP BY `album`) AS `song` SET `album`.`song_count` = `song`.`song_count` WHERE `album`.`song_count` != `song`.`song_count` AND `album`.`id` = `song`.`album`;
```
```
UPDATE `album`, (SELECT COUNT(DISTINCT(`song`.`artist`)) AS `artist_count`, `album` FROM `song` LEFT JOIN `catalog` ON `catalog`.`id` = `song`.`catalog` WHERE `catalog`.`enabled` = '1' GROUP BY `album`) AS `song` SET `album`.`artist_count` = `song`.`artist_count` WHERE `album`.`artist_count` != `song`.`artist_count` AND `album`.`id` = `song`.`album`;
```
```
REPLACE INTO `update_info` SET `key`= 'album_group', `value`= (SELECT COUNT(DISTINCT(`album`.`id`)) AS `count` FROM `album` WHERE `id` in (SELECT MIN(`id`) from `album` GROUP BY `album`.`prefix`, `album`.`name`, `album`.`album_artist`, `album`.`release_type`, `album`.`release_status`, `album`.`mbid`, `album`.`year`, `album`.`original_year`));
```

**Comment by basti0001** [comment]
ty 4 your help lachlan-00. Guess this can be closed now and all other running into this hopefully will find it with google ;-)
