### ISSUE TITLE
React Client Bugged?

### ISSUE THREAD

**Issue by izyspania** [ampache/ampache#3120]
I cant get react client to work (i just want to try it out, would be great if it worked).
https://github.com/ampache/ampache/tree/react-client

im getting this when i try to build it:

```
🚨 Build failed.
@parcel/optimizer-cssnano: /home/ubuntu/ampache/client/components/Header/index.styl:75:2: Missed semicolon
```

I removed all the css from the file just for the sake of testing then and i end up with this:

```
parcel/optimizer-terser: "Export" statement may only appear at the top level
/home/ubuntu/ampache/client/node_modules/react-inlinesvg/esm/types.js:1:0
> 1 | export {};
>   | ^ "Export" statement may only appear at the top level
  2 | //# sourceMappingURL=types.js.map
```

removed export {}; from that file and successful build. 
i copied client folder to /public and going to:
http://server/client - 403 Forbidden
http://server/client/index.html - blank page
http://server/client/dist/ - 403 Forbidden
http://server/client/dist/index.html  - getting an login page that doesnt work https://i.imgur.com/MNTw90V.png

Am i missing something? Any tips ?

Edit: Building on windows i get this: https://i.imgur.com/UWdrzcr.png
i got it to build on windows but im still getting a blank page, the soruce of the page:

```
<html>
<body>
<!--StartFragment-->



<!DOCTYPE html>
  | <html lang="en">
  | <head>
  | <meta
  | name="viewport"
  | content="width=device-width, height=device-height, initial-scale=1.0, minimum-scale=1.0"
  | />
  | <meta name="apple-mobile-web-app-capable" content="yes" />
  | <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  | <meta name="apple-mobile-web-app-title" content="Ampache" />
  | <link rel="apple-touch-icon" href="/images/ampache-dark.png" />
  | <link rel="manifest" href="./manifest.webmanifest" />
  | <title>Ampache</title>
  | </head>
  | <body>
  | <noscript>
  | You need to enable JavaScript to run this app.
  | </noscript>
  | <div id="root" style="height: 100%; display: flex; flex-direction: column;"></div>
  | <div id="modalView"></div>
  | <script type="module" src="./main.tsx"></script>
  | </body>
  | </html>
 

<br class="Apple-interchange-newline"><!--EndFragment-->
</body>
</html>
```
debug from php -S

```
[Wed Dec 15 06:54:03 2021] 192.168.100.6:39764 [200]: (null) /
[Wed Dec 15 06:54:03 2021] 192.168.100.6:39764 Closing
[Wed Dec 15 06:54:04 2021] 192.168.100.6:39766 [200]: (null) /main.tsx
[Wed Dec 15 06:54:04 2021] 192.168.100.6:39766 Closing
[Wed Dec 15 06:54:04 2021] 192.168.100.6:39770 Accepted
[Wed Dec 15 06:54:04 2021] 192.168.100.6:39770 [404]: (null) /favicon.ico - No such file or directory
[Wed Dec 15 06:54:04 2021] 192.168.100.6:39772 Accepted
[Wed Dec 15 06:54:04 2021] 192.168.100.6:39770 Closing
[Wed Dec 15 06:54:04 2021] 192.168.100.6:39772 [200]: (null) /images/ampache-dark.png
[Wed Dec 15 06:54:04 2021] 192.168.100.6:39772 Closing
[Wed Dec 15 06:54:24 2021] 192.168.100.6:39774 Accepted
[Wed Dec 15 06:54:24 2021] 192.168.100.6:39776 Accepted
[Wed Dec 15 06:54:24 2021] 192.168.100.6:39774 [200]: (null) /
[Wed Dec 15 06:54:24 2021] 192.168.100.6:39774 Closing
[Wed Dec 15 06:54:24 2021] 192.168.100.6:39776 [200]: (null) /main.tsx
[Wed Dec 15 06:54:24 2021] 192.168.100.6:39776 Closing
[Wed Dec 15 06:54:24 2021] 192.168.100.6:39778 Accepted
[Wed Dec 15 06:54:24 2021] 192.168.100.6:39778 [200]: (null) /images/ampache-dark.png
[Wed Dec 15 06:54:24 2021] 192.168.100.6:39778 Closing
```

**Comment by izyspania** [comment]
i think it has some dependency issue, with some modifications i made it compile as you see but it doesnt work , ill post the logs when u try to build it without any modification in case someone wants to fix it maybe it will help.

```
www-data@instance-1:~/html/ampache/client$ yarn
yarn install v1.22.17
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > react-async-popup@0.0.6" has incorrect peer dependency "react@^16.0.0".
warning " > react-debounce-input@3.2.3" has incorrect peer dependency "react@^15.3.0 || ^16.0.0".
warning " > react-input-range@1.3.0" has incorrect peer dependency "react@^15.0.0 || ^16.0.0".
warning " > react-input-range@1.3.0" has incorrect peer dependency "react-dom@^15.0.0 || ^16.0.0".
warning " > react-loading@2.0.3" has unmet peer dependency "prop-types@^15.6.0".
warning "react-spring > @react-spring/konva@9.0.0-rc.3" has unmet peer dependency "konva@>=2.6".
warning "react-spring > @react-spring/konva@9.0.0-rc.3" has unmet peer dependency "react-konva@>=16.8".
warning "react-spring > @react-spring/native@9.0.0-rc.3" has unmet peer dependency "react-native@>=0.58".
warning "react-spring > @react-spring/three@9.0.0-rc.3" has unmet peer dependency "react-three-fiber@>=4.0".
warning "react-spring > @react-spring/three@9.0.0-rc.3" has unmet peer dependency "three@>=0.115".
warning "react-spring > @react-spring/zdog@9.0.0-rc.3" has unmet peer dependency "react-zdog@>=1.0".
warning "react-spring > @react-spring/zdog@9.0.0-rc.3" has unmet peer dependency "zdog@>=1.0".
warning "react-spring > @react-spring/core > use-memo-one@1.1.1" has incorrect peer dependency "react@^16.8.0".
[4/4] Building fresh packages...
Done in 190.35s.
www-data@instance-1:~/html/ampache/client$
```
```
www-data@instance-1:~/html/ampache/client$ yarn build
yarn run v1.22.17
$ yarn clean && parcel build index.html
$ rm -rf dist .parcel-cache
🚨 Build failed.
@parcel/optimizer-cssnano: /var/www/html/ampache/client/components/Header/index.styl:75:2: Missed semicolon
CssSyntaxError: /var/www/html/ampache/client/components/Header/index.styl:75:2: Missed semicolon
    at Input.error (/var/www/html/ampache/client/node_modules/postcss/lib/input.js:126:16)
    at Parser.checkMissedSemicolon (/var/www/html/ampache/client/node_modules/postcss/lib/parser.js:601:22)
    at Parser.decl (/var/www/html/ampache/client/node_modules/postcss/lib/parser.js:284:46)
    at Parser.other (/var/www/html/ampache/client/node_modules/postcss/lib/parser.js:131:18)
    at Parser.parse (/var/www/html/ampache/client/node_modules/postcss/lib/parser.js:75:16)
    at parse (/var/www/html/ampache/client/node_modules/postcss/lib/parse.js:17:12)
    at new LazyResult (/var/www/html/ampache/client/node_modules/postcss/lib/lazy-result.js:64:16)
    at Processor.<anonymous> (/var/www/html/ampache/client/node_modules/postcss/lib/processor.js:142:12)
    at Processor.process (/var/www/html/ampache/client/node_modules/postcss/lib/processor.js:121:23)
    at Object.optimize (/var/www/html/ampache/client/node_modules/@parcel/optimizer-cssnano/lib/CSSNanoOptimizer.js:38:68)
⠹ Optimizing index.html...
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
www-data@instance-1:~/html/ampache/client$
```

**Comment by izyspania** [comment]
update: using  npx check-peer-dependencies --yarn --findSolutions

```
Searching for solutions for 5 missing dependencies...

  ❌  Unable to find a version of react that satisfies the following peerDependencies: ^16.8.0 || ^17.0.0 and >=16.6.0 and >=18.0 and 18.0.0-rc.0-next-f2a59df48-20211208 and >=16.13 and >=17.0 and >=16.8 and ^16.0.0 and >=16 and ^15.3.0 || ^16.0.0 || ^17.0.0 and >= 0.14.0 < 18.0.0 and ^16.14.0 and >=16.8.1 and ^15.0.0 || ^16.0.0 || ^17.0.0 and ^15.0.0 || ^16.0.0 and >=16.8.0 and ^17.0.2 and >=0.14.0 and 17.0.2 and >=15 and ^0.14.0 || ^15.0.0 || ^16.0.0 || ^17.0.0 and ^16.8.0  || ^17.0.0 and >=16.11 and >= 16.8.0
```

**Comment by AshotN** [comment]
The client against the API is really out of date, and the dependencies need to be updated as well. I'm going to go through it and see if I can get it working again.

**Comment by AshotN** [comment]
It should be working now. Some functionality may have possibly been broken. But it builds.
