### ISSUE TITLE
Issue with DAAP / Winamp

### ISSUE THREAD

**Issue by adamsih300u** [ampache/ampache#3183]
### Describe the bug
Enabled the DAAP plugin and configured Apache to support the use of DAAP, also configured Avahi-Daemon.

When using the last version of Winamp with the ML-DAAP plugin, the Winamp library is populated with media from Ampache. When selecting any file to play, the following errors are output in the Apache debug log on the Ampache server:

```PHP Fatal error:  Uncaught Error: Class 'flac' not found in /var/www/ampache/src/Module/Api/Daap_Api.php:437\nStack trace:\n#0 [internal function]: Ampache\\Module\\Api\\Daap_Api::databases()\n#1 /var/www/ampache/src/Module/Api/DaapApiApplication.php(70): call_user_func()\n#2 /var/www/ampache/public/daap/index.php(34): Ampache\\Module\\Api\\DaapApiApplication->run()\n#3 {main}\n  thrown in /var/www/ampache/src/Module/Api/Daap_Api.php on line 437```

```[Fri Feb 25 20:29:32.777315 2022] [php7:error] [pid 25632] [client 192.168.80.234:62529] PHP Fatal error:  Uncaught Error: Class 'm4a' not found in /var/www/ampache/src/Module/Api/Daap_Api.php:437\nStack trace:\n#0 [internal function]: Ampache\\Module\\Api\\Daap_Api::databases()\n#1 /var/www/ampache/src/Module/Api/DaapApiApplication.php(70): call_user_func()\n#2 /var/www/ampache/public/daap/index.php(34): Ampache\\Module\\Api\\DaapApiApplication->run()\n#3 {main}\n  thrown in /var/www/ampache/src/Module/Api/Daap_Api.php on line 437```

### To reproduce

Install Ampache; enable DAAP plugin and configure Apache to serve the virtual host on port 3689.

Install Winamp with the ML-DAAP plugin. Run Winamp, wait for the media library to populate with the Ampache media.

Double click any media. Winamp won't play, and skips to other media in the generated playlist. This occurs with MP3, M4A (ALAC) and FLAC media.

### Expected behavior
Winamp should have played the media.

## Environment

* Ampache version: Current Devel
* Web server + version: Apache/2.4.41
* Server operating system: Ubuntu 20.04
* Client operating system: Windows 10

### Client type

* DAAP

## Settings

```
; The local http url of your server.
; This is used to access the server from within the
; same host where ampache is running.
; For example, if the ampache server is not
; directly accessed via the public domain but via a reverse
; proxy, local_web_path would need to be changed
; to a localhost URL.
; If not set, retrieved automatically from server information.
; DEFAULT: none
local_web_path = "http://localhost/"
```
```
<VirtualHost _default_:3689>
    DocumentRoot /var/www/ampache/public/daap/

    SetEnv nokeepalive
    SetEnv downgrade-1.0
    SetEnv force-response-1.0

    <Directory "/var/www/ampache/public/daap/">
        Options Indexes FollowSymLinks MultiViews
        AllowOverride all
        Require all granted
    </Directory>

    LogLevel debug
    ErrorLog ${APACHE_LOG_DIR}/daap-error.log
    CustomLog ${APACHE_LOG_DIR}/daap-access.log combined
```

## Logs

```PHP Fatal error:  Uncaught Error: Class 'flac' not found in /var/www/ampache/src/Module/Api/Daap_Api.php:437\nStack trace:\n#0 [internal function]: Ampache\\Module\\Api\\Daap_Api::databases()\n#1 /var/www/ampache/src/Module/Api/DaapApiApplication.php(70): call_user_func()\n#2 /var/www/ampache/public/daap/index.php(34): Ampache\\Module\\Api\\DaapApiApplication->run()\n#3 {main}\n  thrown in /var/www/ampache/src/Module/Api/Daap_Api.php on line 437```

```[Fri Feb 25 20:29:32.777315 2022] [php7:error] [pid 25632] [client 192.168.80.234:62529] PHP Fatal error:  Uncaught Error: Class 'm4a' not found in /var/www/ampache/src/Module/Api/Daap_Api.php:437\nStack trace:\n#0 [internal function]: Ampache\\Module\\Api\\Daap_Api::databases()\n#1 /var/www/ampache/src/Module/Api/DaapApiApplication.php(70): call_user_func()\n#2 /var/www/ampache/public/daap/index.php(34): Ampache\\Module\\Api\\DaapApiApplication->run()\n#3 {main}\n  thrown in /var/www/ampache/src/Module/Api/Daap_Api.php on line 437```

**Comment by lusum** [comment]
I have tried daap using rhythmbox and the support is broken.

**Comment by manuelglez86** [comment]
As I understand DAAP hasnt been mainteined for a while.

can you post the URL that your changa generates to see if something is missing?

**Comment by lusum** [comment]
I have talked about this with @lachlan-00 

After the patch my client send

/databases/1/items/4.mp3?session-id=7

and the server generates an url like this:

http://x.x.x.x:3689/ampache/play/ssid/261c54c46a9568d36640dde2eaec2bfa/type/song/oid/2/uid/0/client/GStreamer_souphttpsrc_1.18.5_libsoup_2.72.0/transcode_to/mp3/player/api/name/myfile.mp3

but, giving uid 0 ( not valid ), but session valid the server doesn't send nothing.

**Comment by lusum** [comment]
Forced uid = -1 , the music part of daap should work ( after pull request )
