### ISSUE TITLE
"Trust anchor for certification path not found" error

### ISSUE THREAD

**Issue by pled** [ampache/ampache#3973]
## Description

Hi, I need you expertise to understand what is wrong in my config. I hope you can help me.
So I am running Power Ampache 2 v1.00.60-fdroid on the smartphone (GrapheneOS).
It is most probably not an issue with Power Ampache 2, rather with my config, but I am a bit lost with my problem, and my knowledge with certificate is low.

So I run a docker instance of Nextcloud using Swag as a proxy (provided by linuxserver.io, the stack combines Nextcloud + Mariadb + Swag). Swag is essentially nginx + fail2ban + letsencrypt cert validation built-in.
- Swag logs show that Letsencrypt certificate is OK for my domain (xxx.yyy.fr), Nextcloud instance is a subdomain of it (nextcloud.xxx.yyy.fr).

I can connect to Nextcloud music instance using my android smartphone browser (Grapheneos & Vanadium) with HTTPS connection using URL provided by Nextcloud : https://nextcloud.xxx.yyy.fr/apps/music/ampache). See screenshot below.

But connection using Power Ampache 2 is impossible. Logs shows : 

```
2024-06-23 15:51:54
retrofit2.HttpException: HTTP 404 { "exception" : "java.security.cert.CertPathValidatorException: Trust anchor for certification path not found." }
    at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53)
    at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
    at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:535)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
    at java.lang.Thread.run(Thread.java:1012)

authorize() - cannot load data HttpException {"code":404,"message":"{ \"exception\" : \"java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.\" }","detailMessage":"HTTP 404 { \"exception\" : \"java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.\" }","stackTrace":[],"suppressedExceptions":[]}

```

I found this from the nginx access.log file when using Power Ampache 2 :

`92.xxx.yyy.zzz - - [23/Jun/2024:18:11:56 +0200] "GET /apps/music/ampache/server/json.server.php?action=handshake&auth=0dc8eab854xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx289e9ded5423&user=xxxxxxx&timestamp=1719159117 HTTP/2.0" 404 146 "-" "PowerAmpache2-1.00-60-fdroid" 
`

### To reproduce

1. Run Power Ampache 2 on Android, and try to connect to Nextclous Music server.
4. Login Power Ampache 2 with demo server (Dogmazic), and look at logs. See errors

### Screenshots

Screenshot about certificate from browser connection : 

![Screenshot_20240623-172423-1](https://github.com/ampache/ampache/assets/2879483/3e93b740-91d0-41f3-90b4-47616ef4735b)

## Environment

Power Apache 2 version : 1.00-60-fdroid
Nextcloud version : 25.0.13
Operating system and version: Armbian 24.5.1 bookworm (x32)
Apache or nginx version : 1.20.2
PHP version : 8.1.16

**Comment by lachlan-00** [comment]
that access log says there was a 404 on the handshake

does a ping work?

```
/apps/music/ampache/server/json.server.php?action=ping
```

**Comment by pled** [comment]
Hum, no, I got "Not Found" from nginx. I've enable usb debug on smartphone, and this is what I get : 

![Capture d’écran du 2024-06-25 09-49-24](https://github.com/ampache/ampache/assets/2879483/13272c3e-c559-4ec9-8654-836939fbf745)

When setting up the docker stack, I have declared the following for swag : 
      - URL=xxx.yyy.fr
      - SUBDOMAINS=nextcloud

And for Nextcloud `config.php` file, I have set : 

```
  'trusted_domains' => 
  array (
    0 => 'nextcloud.xxx.yyy.fr',
  ),
```

**Comment by lachlan-00** [comment]
Reinstalled the music app and I get the default ping response from the api
![image](https://github.com/ampache/ampache/assets/1305249/4b9ddced-40a5-4091-955c-1c28453ef27b)

`https://nextcloud/apps/music/ampache/server/json.server.php?action=ping` nextcloud 28 and music2.0.0

There may be an nginx issue with nextcloud rewrites? I'm on Apache so i haven't really used nginx very much.

**Comment by pled** [comment]
OK, so I will investigate in that direction (nginx). My version is probably not up to date as I am still using x32 software because my SBC is an odroid-hc2 ... :-( . But it runs well, so I am reluctant to throw it away...

Thanks a lot for your help, very helpful. :+1:

**Comment by lachlan-00** [comment]
there may be issues between the nextcloud verison and the music version too. but that would probably not let you install so maybe not an issue

**Comment by pled** [comment]
Actually, I did not notice I was running such old nextcloud version, so I went into updates : 25 -> 26 -> 27 -> 28  -> 29. So now I am running 29.0.3  and Music 2.0.0.
But no change, still the same error.
Going to Administration page, I saw a message/warning like below : 

`Your web server doesn't support `.mjs` files using the MIME JavaScript type. This disrupts certain applications by preventing browsers from executing JavaScript files. You need to configure your web server to handle `.mjs` files with the `text/javascript` or `application/javascript` MIME types.
`

So I modified `/etc/nginx/mime.types` file and changed `application/javascript js;` to `application/javascript js mjs;`.
But I still have the same message/warning, and the same error while trying to connect from Power Ampache 2.

I also try to add `/server/xml.server.php` to https://nextcloud.xxx.yyy.fr/apps/music/ampache URL as recommended by Nextcloud, without success. :disappointed:

**Comment by pled** [comment]
Just for information, mime-types error message is resolved (file to update was `Nextcloud/config/nginx/site-confs/default.conf` like explained [here](https://docs.nextcloud.com/server/stable/admin_manual/installation/nginx.html#nginx-config)). So no more errors, but issue is still there. 

But the good news is that there is a open issue on Nextcloud Music app: 
https://github.com/owncloud/music/issues/851

I don't feel alone anymore ! :wink:

**Comment by pled** [comment]
**Correction** : applying `try_files` directive as mentioned by @aleixq in the https://github.com/owncloud/music/issues/851 does solve the issue (I made a mistake yesterday in my testing). 

I am now able to connect Power Ampache 2 to my Nextcloud instance ! :+1:

**Comment by lachlan-00** [comment]
did you edit the default location or add a separate one?

if you add a separate location block it would be good to go into the default templates  as part of the documentation issues

**Comment by pled** [comment]
I saw your suggestion, but was not sure sure how to apply it. But I would be happy to test it and report the issue to the nextcloud documentation project (with a clean solution).

Can you guide me ? I can create a new location as your advice in the server config file, but I am not sure how to manage the  `fastcgi_split_path_info` case ? 

> and then remove the fastcgi_split_path_info or copy the default settings without it into the folder

**Comment by lachlan-00** [comment]
i think you just need to add a location above the lines you changed in the conf.

it'd be something like this if following the link in the issue https://docs.nextcloud.com/server/21/admin_manual/installation/nginx.html#nextcloud-in-the-webroot-of-nginx

```
    location ~ ^/apps/music/ampache/server/.*\.php$ {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        set $path_info $fastcgi_path_info;

        try_files $fastcgi_script_name /index.php$fastcgi_script_name?$args;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $path_info;
        fastcgi_param HTTPS on;

        fastcgi_param modHeadersAvailable true;         # Avoid sending the security headers twice
        fastcgi_param front_controller_active true;     # Enable pretty urls
        fastcgi_pass php-handler;

        fastcgi_intercept_errors on;
        fastcgi_request_buffering off;
    }

    # Ensure this block, which passes PHP files to the PHP process, is above the blocks
    # which handle static assets (as seen below). If this block is not declared first,
    # then Nginx will encounter an infinite rewriting loop when it prepends `/index.php`
    # to the URI, resulting in a HTTP 500 error response.
    location ~ \.php(?:$|/) {
        # Required for legacy support
        rewrite ^/(?!index|remote|public|cron|core\/ajax\/update|status|ocs\/v[12]|updater\/.+|oc[ms]-provider\/.+|.+\/richdocumentscode\/proxy) /index.php$request_uri;

        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        set $path_info $fastcgi_path_info;

        try_files $fastcgi_script_name =404;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $path_info;
        fastcgi_param HTTPS on;

        fastcgi_param modHeadersAvailable true;         # Avoid sending the security headers twice
        fastcgi_param front_controller_active true;     # Enable pretty urls
        fastcgi_pass php-handler;

        fastcgi_intercept_errors on;
        fastcgi_request_buffering off;
    }
```

**Comment by pled** [comment]
Thanks a lot for your help ! It works like a charm, and looks like a very clean solution ! :+1: 
I will create an issue on the Nextcloud documentation project with all that information, and they may update the documentation with that solution.
Thanks again, I am very happy to have now my Nextcloud music available from outside home !

**Comment by fufroma** [comment]
@pled if all is fine for you, can you close this issue?

**Comment by pled** [comment]
@fufroma  Yes, issue can be closed. 

At the end, I used the solution proposed by the issue I created in the nextcloud documentation : 
https://github.com/nextcloud/documentation/issues/11951

It is about modifying the existing rewrite line rather than adding a new location (simpler).
