### ISSUE TITLE
No icons after update

### ISSUE THREAD

**Issue by bacinet02** [ampache/ampache#4074]
## Description
Hello,
I have updated from 5.5.x to 7.0.1.
It works fine, but ... 
All the icons are now question marks. FOr example:
![image](https://github.com/user-attachments/assets/90331121-cd1a-47c3-b0d1-3f16fd57d232)

In the apache access log, I have no errors but only:
```
a.b.c.d - - [10/Nov/2024:18:43:12 +0200] "GET /song.php?action=show_song&song_id=84513 HTTP/1.1" 200 20281 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0"
a.b.c.d - - [10/Nov/2024:18:43:13 +0200] "GET /util.php HTTP/1.1" 200 477 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0"
```

Any idea?
Thanks for answer :-)

**Comment by lachlan-00** [comment]
npm is required to build the icons and JS https://github.com/ampache/ampache/wiki/ampache7-for-admins#npm-is-required-for-js-package-installation

once you do that you'll be fine, the ? is there for missing icons and doesn't require NPM

```
npm install
npm run build
```

**Comment by bacinet02** [comment]
Thanks.
I have installed it, but I have errors:
```
...
added 174 packages from 109 contributors and audited 211 packages in 401.675s

59 packages are looking for funding
  run `npm fund` for details

found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
root@xyz:/home/html/ampache# npm run build

> ampache@1.0.0 build /home/html/ampache
> vite build --minify false

/home/html/ampache/node_modules/vite/bin/vite.js:2
import { performance } from 'node:perf_hooks'
       ^

SyntaxError: Unexpected token {
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ampache@1.0.0 build: `vite build --minify false`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ampache@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-11-11T08_41_59_203Z-debug.log
```
And the logfile:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'build' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle ampache@1.0.0~prebuild: ampache@1.0.0
6 info lifecycle ampache@1.0.0~build: ampache@1.0.0
7 verbose lifecycle ampache@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle ampache@1.0.0~build: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/html/ampache/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle ampache@1.0.0~build: CWD: /home/html/ampache
10 silly lifecycle ampache@1.0.0~build: Args: [ '-c', 'vite build --minify false' ]
11 silly lifecycle ampache@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle ampache@1.0.0~build: Failed to exec build script
13 verbose stack Error: ampache@1.0.0 build: `vite build --minify false`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid ampache@1.0.0
15 verbose cwd /home/html/ampache
16 verbose Linux 5.4.0-200-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error ampache@1.0.0 build: `vite build --minify false`
22 error Exit status 1
23 error Failed at the ampache@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Thanks for help. I have no skills for npm :-(

**Comment by lachlan-00** [comment]
I think your node versions might be too old. are you on Ubuntu LTS?

```
2 info using npm@6.14.4
3 info using node@v10.19.0
```

If you can't update that and this is using git i'd suggest getting an zip and extracting over your install. Not much will be changing in npm land for a while so it would be fine to extract over a git install and then git reset any changes

php 8.2 = https://github.com/ampache/ampache/releases/download/7.0.1/ampache-7.0.1_all_php8.2.zip
php8.3 = https://github.com/ampache/ampache/releases/download/7.0.1/ampache-7.0.1_all_php8.3.zip

**Comment by bacinet02** [comment]
Hello,
Thanks for answer.

I have upgraded my server. But I have still an error:

`
root@xyz:/home/html/ampache# npm -v
8.5.1
root@xyz:/home/html/ampache# node -v
v12.22.9
root@xyz:/home/html/ampache# npm run build

> ampache@1.0.0 build
> vite build --minify false

file:///home/html/ampache/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
`

I have installed vite.
And tested it:

`
root@3oj0:/home/html/ampache# vite build --minify false
vite: invalid option -- '-'
vite: invalid option -- 'm'
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Aborted (core dumped)
`

Is it normal?

Thanks for answer :-)

**Comment by NatureMuncher** [comment]
I'm having the same issue:
```
user@host :~/html/ampache$ npm run build

> ampache@1.0.0 build
> vite build --minify false

file:///var/www/html/ampache/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)
```

**Comment by NatureMuncher** [comment]
I did download the .zip and I'm operational again just with a pending update:
`312765c0cc5e12a4208b70d2739a021be144230d`
Is that safe to upgrade to?

**Comment by lachlan-00** [comment]
yeah the node data won't be removed with updates

**Comment by lachlan-00** [comment]
those areas are pretty static and not tracked by git so can be manually done.

the older npm versions won't be able to install all the vite packages / requirements. i might do a script to manually do this from a zip

**Comment by barcoboy** [comment]
Thank you @lachlan-00 for posting this.  It had prevented me from updating to version 7 for a while now, and with these two npm commands, my question marks are gone and it looks great!

**Comment by lachlan-00** [comment]
next release onwards we've tagged a version string on the css files to force an update when the version string changes

54eb43f4f40f0de33bd930746b3c46e782ec97cd

obviously doesn't help you now but it will be helpful in future for major changes.

**Comment by fufroma** [comment]
@lachlan-00 you talked about doing a script to manually do this from a zip. Do you want to keep this issue open for this or can we close it?

**Comment by lachlan-00** [comment]
keep it open i'll make one when i'm free soon, just been focusing on tags this week so far

**Comment by lachlan-00** [comment]
closing as this has been heavily updated and tested
