### ISSUE TITLE
AlbumDisk::$album must not be accessed before initialization

### ISSUE THREAD

**Issue by erezschatz** [ampache/ampache#4090]
### Describe the bug
I was not able to play songs or playlists, or check the song's page, I've checked the logs and found the error in the title, once I've commented that part all functions resumed normally (at least from my perspective). I am not aware of whether other elements were not working.

### To reproduce

1. Go to a playlist page (or from the playlists page)
2. Click on play all (or try playing a song)
3. Nothing happens
4. Also, clicking on any song only shows its title and nothing more

## Environment

* Ampache version: latest develop

### Client type

* Web

## Logs

```
2024-12-08T10:56:44+00:00 [erez] (Ampache\Module\System\Session) -> 1ng6jpbp5esspgfrnpelepe1o9 has been extended to Sun, 08 Dec 2024 11:56:44 +0000 extension length 3600
2024-12-08T10:56:44+00:00 [erez] (Ampache\Module\Application\ApplicationRunner) -> Found handler "Ampache\Module\Application\Song\ShowSongAction" for action "show_song"
2024-12-08T10:56:44+00:00 [erez] (Ampache\Module\System\Session) -> Session created: 9dec3f964ffa611c436e3f479123d8ea
2024-12-08T10:56:44+00:00 [erez] (/var/www/html/ampache/src/Repository/Model/AlbumDisk.php:382) -> Typed property Ampache\Repository\Model\AlbumDisk::$album must not be accessed before initialization
2024-12-08T10:56:44+00:00 [erez] (Ampache\Module\System\Session) -> Writing to 1ng6jpbp5esspgfrnpelepe1o9 with expiration 1733659004
```

**Comment by lachlan-00** [comment]
i think i see this. it's not finding info and not creating the empty album

f13576a96dbca7126cfb38b779447cded0061450

will fix that. you sohuld update from tags to see if it creates the albums and disks for you after that

**Comment by fufroma** [comment]
@erezschatz can we close this issue ?

**Comment by lachlan-00** [comment]
after https://github.com/ampache/ampache/pull/4094/commits/5f8e48042e4ed634b2ec1a61cbe1a4006e2f6222 you should be all good.

7.1.1 out now

**Comment by fufroma** [comment]
@lachlan-00 similar issue:

https://play.dogmazic.net/artists.php?action=show_all_songs&artist=2699
`2024-12-20T14:06:04+00:00 [-1] (src/Repository/Model/Song.php:1875) -> Typed property Ampache\Repository\Model\Song::$album_disk must not be accessed before initialization`

**Comment by barcoboy** [comment]
@lachlan-00, I believe I have the same issue when running a catalog update or clean.  Seeing this in my Apache logs:

PHP Fatal error:  Uncaught Error: Typed property Ampache\\Repository\\Model\\Song::$album_disk must not be accessed before initialization in /var/www/ampache/src/Repository/Model/Catalog.php:2724\nStack trace:\n#0 /var/www/ampache/src/Repository/Model/Catalog.php(2509): Ampache\\Repository\\Model\\Catalog::update_song_from_tags()\n#1 /var/www/ampache/src/Repository/Model/Catalog.php(2374): Ampache\\Repository\\Model\\Catalog::update_media_from_tags()\n#2 /var/www/ampache/src/Module/Catalog/Catalog_local.php(716): Ampache\\Repository\\Model\\Catalog::update_single_item()\n#3 /var/www/ampache/src/Module/Catalog/Catalog_local.php(633): Ampache\\Module\\Catalog\\Catalog_local->_verify_chunk()\n#4 /var/www/ampache/src/Repository/Model/Catalog.php(3522): Ampache\\Module\\Catalog\\Catalog_local->verify_catalog_proc()\n#5 /var/www/ampache/src/Repository/Model/Catalog.php(4023): Ampache\\Repository\\Model\\Catalog->verify_catalog()\n#6 /var/www/ampache/src/Module/Api/SseApiApplication.php(92): Ampache\\Repository\\Model\\Catalog::process_action()\n#7 /var/www/ampache/public/server/sse.server.php(32): Ampache\\Module\\Api\\SseApiApplication->run()\n#8 {main}\n  thrown in /var/www/ampache/src/Repository/Model/Catalog.php on line 2724

**Comment by fufroma** [comment]
`Uncaught Error: Typed property Ampache\Repository\Model\Song::$album_disk must not be accessed before initialization`

Fix in https://github.com/ampache/ampache/pull/4096

**Comment by lachlan-00** [comment]
the fix is in but a workaround, what we'll have here is a non-song that ampache is trying to open so i'll work out where that link is coming from and but a verification before trying to load an empty song.

**Comment by fufroma** [comment]
@lachlan-00 do you want to keep this issue open?

**Comment by arno1979** [comment]
I had this happen to me on a catalog verify run via CLI:
```ampache/bin/cli run:updateCatalog [catalog] -e```

Log output reads like this:
```2025-01-23T08:35:54+01:00 [ampache] (Ampache\Module\System\Dba) -> Database connection...
2025-01-23T08:35:54+01:00 [System] (local.catalog) -> Verify starting on [catalog]
2025-01-23T08:35:54+01:00 [System] (local.catalog) -> found 7586 song files to update. (last_update: 1682148523)
2025-01-23T08:35:54+01:00 [System] (local.catalog) -> catalog [catalog] starting verify song on chunk 1/1
2025-01-23T08:35:54+01:00 [System] (local.catalog) -> catalog [catalog] starting verify song on chunk 2/1
2025-01-23T08:35:54+01:00 [System] (Ampache\Repository\Model\Catalog) -> Reading tags from /mnt/music/[catalog]/[album]/[track].mp3

**Comment by fufroma** [comment]
@arno1979 which ampache version?

**Comment by arno1979** [comment]
@fufroma 7.2.0

**Comment by fufroma** [comment]
@arno1979 can you check if 7.3 is OK and, if so, close this issue?

**Comment by arno1979** [comment]
Just did a verify on two medium sized catalogs with 7.3.0 and looks good to me. Thanks!
I can't close the issue though, as I did not create it.

**Comment by fufroma** [comment]
@lachlan-00 I think you can close this issue
